// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lecturer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LecturerServiceClient is the client API for LecturerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LecturerServiceClient interface {
	CreateLecturer(ctx context.Context, in *CreateLecturerRequest, opts ...grpc.CallOption) (*CreateLecturerResponse, error)
	GetLecturerByName(ctx context.Context, in *GetLecturerRequest, opts ...grpc.CallOption) (*GetLecturerResponse, error)
	UpdateLecturer(ctx context.Context, in *UpdateLecturerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteLecturer(ctx context.Context, in *DeleteLecturerRequest, opts ...grpc.CallOption) (*DeleteLecturerResponse, error)
	GetLecturers(ctx context.Context, in *GetLecturersRequest, opts ...grpc.CallOption) (LecturerService_GetLecturersClient, error)
}

type lecturerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLecturerServiceClient(cc grpc.ClientConnInterface) LecturerServiceClient {
	return &lecturerServiceClient{cc}
}

func (c *lecturerServiceClient) CreateLecturer(ctx context.Context, in *CreateLecturerRequest, opts ...grpc.CallOption) (*CreateLecturerResponse, error) {
	out := new(CreateLecturerResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/CreateLecturer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) GetLecturerByName(ctx context.Context, in *GetLecturerRequest, opts ...grpc.CallOption) (*GetLecturerResponse, error) {
	out := new(GetLecturerResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/GetLecturerByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) UpdateLecturer(ctx context.Context, in *UpdateLecturerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/UpdateLecturer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) DeleteLecturer(ctx context.Context, in *DeleteLecturerRequest, opts ...grpc.CallOption) (*DeleteLecturerResponse, error) {
	out := new(DeleteLecturerResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/DeleteLecturer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) GetLecturers(ctx context.Context, in *GetLecturersRequest, opts ...grpc.CallOption) (LecturerService_GetLecturersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LecturerService_serviceDesc.Streams[0], "/lecturer.LecturerService/GetLecturers", opts...)
	if err != nil {
		return nil, err
	}
	x := &lecturerServiceGetLecturersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LecturerService_GetLecturersClient interface {
	Recv() (*GetLecturerResponse, error)
	grpc.ClientStream
}

type lecturerServiceGetLecturersClient struct {
	grpc.ClientStream
}

func (x *lecturerServiceGetLecturersClient) Recv() (*GetLecturerResponse, error) {
	m := new(GetLecturerResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LecturerServiceServer is the server API for LecturerService service.
// All implementations must embed UnimplementedLecturerServiceServer
// for forward compatibility
type LecturerServiceServer interface {
	CreateLecturer(context.Context, *CreateLecturerRequest) (*CreateLecturerResponse, error)
	GetLecturerByName(context.Context, *GetLecturerRequest) (*GetLecturerResponse, error)
	UpdateLecturer(context.Context, *UpdateLecturerRequest) (*emptypb.Empty, error)
	DeleteLecturer(context.Context, *DeleteLecturerRequest) (*DeleteLecturerResponse, error)
	GetLecturers(*GetLecturersRequest, LecturerService_GetLecturersServer) error
	mustEmbedUnimplementedLecturerServiceServer()
}

// UnimplementedLecturerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLecturerServiceServer struct {
}

func (UnimplementedLecturerServiceServer) CreateLecturer(context.Context, *CreateLecturerRequest) (*CreateLecturerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) GetLecturerByName(context.Context, *GetLecturerRequest) (*GetLecturerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLecturerByName not implemented")
}
func (UnimplementedLecturerServiceServer) UpdateLecturer(context.Context, *UpdateLecturerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) DeleteLecturer(context.Context, *DeleteLecturerRequest) (*DeleteLecturerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) GetLecturers(*GetLecturersRequest, LecturerService_GetLecturersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLecturers not implemented")
}
func (UnimplementedLecturerServiceServer) mustEmbedUnimplementedLecturerServiceServer() {}

// UnsafeLecturerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LecturerServiceServer will
// result in compilation errors.
type UnsafeLecturerServiceServer interface {
	mustEmbedUnimplementedLecturerServiceServer()
}

func RegisterLecturerServiceServer(s *grpc.Server, srv LecturerServiceServer) {
	s.RegisterService(&_LecturerService_serviceDesc, srv)
}

func _LecturerService_CreateLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).CreateLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/CreateLecturer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).CreateLecturer(ctx, req.(*CreateLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_GetLecturerByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).GetLecturerByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/GetLecturerByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).GetLecturerByName(ctx, req.(*GetLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_UpdateLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).UpdateLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/UpdateLecturer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).UpdateLecturer(ctx, req.(*UpdateLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_DeleteLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).DeleteLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/DeleteLecturer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).DeleteLecturer(ctx, req.(*DeleteLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_GetLecturers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLecturersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LecturerServiceServer).GetLecturers(m, &lecturerServiceGetLecturersServer{stream})
}

type LecturerService_GetLecturersServer interface {
	Send(*GetLecturerResponse) error
	grpc.ServerStream
}

type lecturerServiceGetLecturersServer struct {
	grpc.ServerStream
}

func (x *lecturerServiceGetLecturersServer) Send(m *GetLecturerResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LecturerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lecturer.LecturerService",
	HandlerType: (*LecturerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLecturer",
			Handler:    _LecturerService_CreateLecturer_Handler,
		},
		{
			MethodName: "GetLecturerByName",
			Handler:    _LecturerService_GetLecturerByName_Handler,
		},
		{
			MethodName: "UpdateLecturer",
			Handler:    _LecturerService_UpdateLecturer_Handler,
		},
		{
			MethodName: "DeleteLecturer",
			Handler:    _LecturerService_DeleteLecturer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLecturers",
			Handler:       _LecturerService_GetLecturers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/lecturer/lecturer.proto",
}
