// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/lecturer/lecturer.proto

package lecturer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lecturer struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string                 `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Lecturer) Reset() {
	*x = Lecturer{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lecturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lecturer) ProtoMessage() {}

func (x *Lecturer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lecturer.ProtoReflect.Descriptor instead.
func (*Lecturer) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{0}
}

func (x *Lecturer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lecturer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Lecturer) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lecturer) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type CreateLecturerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FullName         string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string                 `protobuf:"bytes,3,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateLecturerRequest) Reset() {
	*x = CreateLecturerRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLecturerRequest) ProtoMessage() {}

func (x *CreateLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLecturerRequest.ProtoReflect.Descriptor instead.
func (*CreateLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLecturerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateLecturerRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLecturerRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type CreateLecturerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecturer      *Lecturer              `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLecturerResponse) Reset() {
	*x = CreateLecturerResponse{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLecturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLecturerResponse) ProtoMessage() {}

func (x *CreateLecturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLecturerResponse.ProtoReflect.Descriptor instead.
func (*CreateLecturerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLecturerResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

type GetLecturerByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLecturerByIDRequest) Reset() {
	*x = GetLecturerByIDRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLecturerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByIDRequest) ProtoMessage() {}

func (x *GetLecturerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLecturerByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{3}
}

func (x *GetLecturerByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLecturerByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecturer      *Lecturer              `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLecturerByIDResponse) Reset() {
	*x = GetLecturerByIDResponse{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLecturerByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByIDResponse) ProtoMessage() {}

func (x *GetLecturerByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByIDResponse.ProtoReflect.Descriptor instead.
func (*GetLecturerByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{4}
}

func (x *GetLecturerByIDResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

type GetLecturerByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FullName      string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLecturerByNameRequest) Reset() {
	*x = GetLecturerByNameRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLecturerByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByNameRequest) ProtoMessage() {}

func (x *GetLecturerByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByNameRequest.ProtoReflect.Descriptor instead.
func (*GetLecturerByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{5}
}

func (x *GetLecturerByNameRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetLecturerByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecturer      *Lecturer              `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLecturerByNameResponse) Reset() {
	*x = GetLecturerByNameResponse{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLecturerByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByNameResponse) ProtoMessage() {}

func (x *GetLecturerByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByNameResponse.ProtoReflect.Descriptor instead.
func (*GetLecturerByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{6}
}

func (x *GetLecturerByNameResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

type ListLecturersRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Page             int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FieldOfExpertise string                 `protobuf:"bytes,3,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
	Title            string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListLecturersRequest) Reset() {
	*x = ListLecturersRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersRequest) ProtoMessage() {}

func (x *ListLecturersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersRequest.ProtoReflect.Descriptor instead.
func (*ListLecturersRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{7}
}

func (x *ListLecturersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturersRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

func (x *ListLecturersRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListLecturersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecturers     []*Lecturer            `protobuf:"bytes,1,rep,name=lecturers,proto3" json:"lecturers,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLecturersResponse) Reset() {
	*x = ListLecturersResponse{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersResponse) ProtoMessage() {}

func (x *ListLecturersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersResponse.ProtoReflect.Descriptor instead.
func (*ListLecturersResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{8}
}

func (x *ListLecturersResponse) GetLecturers() []*Lecturer {
	if x != nil {
		return x.Lecturers
	}
	return nil
}

func (x *ListLecturersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListLecturersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturersResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type ListLecturersByFieldOfExpertiseRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FieldOfExpertise string                 `protobuf:"bytes,1,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
	Page             int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListLecturersByFieldOfExpertiseRequest) Reset() {
	*x = ListLecturersByFieldOfExpertiseRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturersByFieldOfExpertiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersByFieldOfExpertiseRequest) ProtoMessage() {}

func (x *ListLecturersByFieldOfExpertiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersByFieldOfExpertiseRequest.ProtoReflect.Descriptor instead.
func (*ListLecturersByFieldOfExpertiseRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{9}
}

func (x *ListLecturersByFieldOfExpertiseRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

func (x *ListLecturersByFieldOfExpertiseRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLecturersByFieldOfExpertiseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecturers     []*Lecturer            `protobuf:"bytes,1,rep,name=lecturers,proto3" json:"lecturers,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLecturersByFieldOfExpertiseResponse) Reset() {
	*x = ListLecturersByFieldOfExpertiseResponse{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturersByFieldOfExpertiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersByFieldOfExpertiseResponse) ProtoMessage() {}

func (x *ListLecturersByFieldOfExpertiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersByFieldOfExpertiseResponse.ProtoReflect.Descriptor instead.
func (*ListLecturersByFieldOfExpertiseResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{10}
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetLecturers() []*Lecturer {
	if x != nil {
		return x.Lecturers
	}
	return nil
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type UpdateLecturerRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string                 `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateLecturerRequest) Reset() {
	*x = UpdateLecturerRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLecturerRequest) ProtoMessage() {}

func (x *UpdateLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLecturerRequest.ProtoReflect.Descriptor instead.
func (*UpdateLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateLecturerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLecturerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateLecturerRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLecturerRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type DeleteLecturerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLecturerRequest) Reset() {
	*x = DeleteLecturerRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLecturerRequest) ProtoMessage() {}

func (x *DeleteLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLecturerRequest.ProtoReflect.Descriptor instead.
func (*DeleteLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteLecturerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLecturerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecturer      *Lecturer              `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLecturerResponse) Reset() {
	*x = DeleteLecturerResponse{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLecturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLecturerResponse) ProtoMessage() {}

func (x *DeleteLecturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLecturerResponse.ProtoReflect.Descriptor instead.
func (*DeleteLecturerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteLecturerResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

type SendEmailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ForceFail     bool                   `protobuf:"varint,4,opt,name=force_fail,json=forceFail,proto3" json:"force_fail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailRequest) Reset() {
	*x = SendEmailRequest{}
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailRequest) ProtoMessage() {}

func (x *SendEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailRequest.ProtoReflect.Descriptor instead.
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{14}
}

func (x *SendEmailRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SendEmailRequest) GetForceFail() bool {
	if x != nil {
		return x.ForceFail
	}
	return false
}

var File_proto_lecturer_lecturer_proto protoreflect.FileDescriptor

const file_proto_lecturer_lecturer_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/lecturer/lecturer.proto\x12\blecturer\x1a\x1bgoogle/protobuf/empty.proto\"{\n" +
	"\bLecturer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12,\n" +
	"\x12field_of_expertise\x18\x04 \x01(\tR\x10fieldOfExpertise\"x\n" +
	"\x15CreateLecturerRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12,\n" +
	"\x12field_of_expertise\x18\x03 \x01(\tR\x10fieldOfExpertise\"H\n" +
	"\x16CreateLecturerResponse\x12.\n" +
	"\blecturer\x18\x01 \x01(\v2\x12.lecturer.LecturerR\blecturer\"(\n" +
	"\x16GetLecturerByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"I\n" +
	"\x17GetLecturerByIDResponse\x12.\n" +
	"\blecturer\x18\x01 \x01(\v2\x12.lecturer.LecturerR\blecturer\"7\n" +
	"\x18GetLecturerByNameRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\"K\n" +
	"\x19GetLecturerByNameResponse\x12.\n" +
	"\blecturer\x18\x01 \x01(\v2\x12.lecturer.LecturerR\blecturer\"\x8b\x01\n" +
	"\x14ListLecturersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12,\n" +
	"\x12field_of_expertise\x18\x03 \x01(\tR\x10fieldOfExpertise\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\xbf\x01\n" +
	"\x15ListLecturersResponse\x120\n" +
	"\tlecturers\x18\x01 \x03(\v2\x12.lecturer.LecturerR\tlecturers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\"\x87\x01\n" +
	"&ListLecturersByFieldOfExpertiseRequest\x12,\n" +
	"\x12field_of_expertise\x18\x01 \x01(\tR\x10fieldOfExpertise\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xd1\x01\n" +
	"'ListLecturersByFieldOfExpertiseResponse\x120\n" +
	"\tlecturers\x18\x01 \x03(\v2\x12.lecturer.LecturerR\tlecturers\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\"\x88\x01\n" +
	"\x15UpdateLecturerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12,\n" +
	"\x12field_of_expertise\x18\x04 \x01(\tR\x10fieldOfExpertise\"'\n" +
	"\x15DeleteLecturerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"H\n" +
	"\x16DeleteLecturerResponse\x12.\n" +
	"\blecturer\x18\x01 \x01(\v2\x12.lecturer.LecturerR\blecturer\"o\n" +
	"\x10SendEmailRequest\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1d\n" +
	"\n" +
	"force_fail\x18\x04 \x01(\bR\tforceFail2\xa5\x05\n" +
	"\x0fLecturerService\x12U\n" +
	"\x0eCreateLecturer\x12\x1f.lecturer.CreateLecturerRequest\x1a .lecturer.CreateLecturerResponse\"\x00\x12K\n" +
	"\x0eUpdateLecturer\x12\x1f.lecturer.UpdateLecturerRequest\x1a\x16.google.protobuf.Empty\"\x00\x12U\n" +
	"\x0eDeleteLecturer\x12\x1f.lecturer.DeleteLecturerRequest\x1a .lecturer.DeleteLecturerResponse\"\x00\x12X\n" +
	"\x0fGetLecturerByID\x12 .lecturer.GetLecturerByIDRequest\x1a!.lecturer.GetLecturerByIDResponse\"\x00\x12^\n" +
	"\x11GetLecturerByName\x12\".lecturer.GetLecturerByNameRequest\x1a#.lecturer.GetLecturerByNameResponse\"\x00\x12R\n" +
	"\rListLecturers\x12\x1e.lecturer.ListLecturersRequest\x1a\x1f.lecturer.ListLecturersResponse\"\x00\x12\x88\x01\n" +
	"\x1fListLecturersByFieldOfExpertise\x120.lecturer.ListLecturersByFieldOfExpertiseRequest\x1a1.lecturer.ListLecturersByFieldOfExpertiseResponse\"\x002N\n" +
	"\vMailService\x12?\n" +
	"\tSendEmail\x12\x1a.lecturer.SendEmailRequest\x1a\x16.google.protobuf.EmptyBMZKgithub.com/LukaDervisevic/MikroservisnaArhitekturaISProjekat/proto/lecturerb\x06proto3"

var (
	file_proto_lecturer_lecturer_proto_rawDescOnce sync.Once
	file_proto_lecturer_lecturer_proto_rawDescData []byte
)

func file_proto_lecturer_lecturer_proto_rawDescGZIP() []byte {
	file_proto_lecturer_lecturer_proto_rawDescOnce.Do(func() {
		file_proto_lecturer_lecturer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lecturer_lecturer_proto_rawDesc), len(file_proto_lecturer_lecturer_proto_rawDesc)))
	})
	return file_proto_lecturer_lecturer_proto_rawDescData
}

var file_proto_lecturer_lecturer_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_lecturer_lecturer_proto_goTypes = []any{
	(*Lecturer)(nil),                                // 0: lecturer.Lecturer
	(*CreateLecturerRequest)(nil),                   // 1: lecturer.CreateLecturerRequest
	(*CreateLecturerResponse)(nil),                  // 2: lecturer.CreateLecturerResponse
	(*GetLecturerByIDRequest)(nil),                  // 3: lecturer.GetLecturerByIDRequest
	(*GetLecturerByIDResponse)(nil),                 // 4: lecturer.GetLecturerByIDResponse
	(*GetLecturerByNameRequest)(nil),                // 5: lecturer.GetLecturerByNameRequest
	(*GetLecturerByNameResponse)(nil),               // 6: lecturer.GetLecturerByNameResponse
	(*ListLecturersRequest)(nil),                    // 7: lecturer.ListLecturersRequest
	(*ListLecturersResponse)(nil),                   // 8: lecturer.ListLecturersResponse
	(*ListLecturersByFieldOfExpertiseRequest)(nil),  // 9: lecturer.ListLecturersByFieldOfExpertiseRequest
	(*ListLecturersByFieldOfExpertiseResponse)(nil), // 10: lecturer.ListLecturersByFieldOfExpertiseResponse
	(*UpdateLecturerRequest)(nil),                   // 11: lecturer.UpdateLecturerRequest
	(*DeleteLecturerRequest)(nil),                   // 12: lecturer.DeleteLecturerRequest
	(*DeleteLecturerResponse)(nil),                  // 13: lecturer.DeleteLecturerResponse
	(*SendEmailRequest)(nil),                        // 14: lecturer.SendEmailRequest
	(*emptypb.Empty)(nil),                           // 15: google.protobuf.Empty
}
var file_proto_lecturer_lecturer_proto_depIdxs = []int32{
	0,  // 0: lecturer.CreateLecturerResponse.lecturer:type_name -> lecturer.Lecturer
	0,  // 1: lecturer.GetLecturerByIDResponse.lecturer:type_name -> lecturer.Lecturer
	0,  // 2: lecturer.GetLecturerByNameResponse.lecturer:type_name -> lecturer.Lecturer
	0,  // 3: lecturer.ListLecturersResponse.lecturers:type_name -> lecturer.Lecturer
	0,  // 4: lecturer.ListLecturersByFieldOfExpertiseResponse.lecturers:type_name -> lecturer.Lecturer
	0,  // 5: lecturer.DeleteLecturerResponse.lecturer:type_name -> lecturer.Lecturer
	1,  // 6: lecturer.LecturerService.CreateLecturer:input_type -> lecturer.CreateLecturerRequest
	11, // 7: lecturer.LecturerService.UpdateLecturer:input_type -> lecturer.UpdateLecturerRequest
	12, // 8: lecturer.LecturerService.DeleteLecturer:input_type -> lecturer.DeleteLecturerRequest
	3,  // 9: lecturer.LecturerService.GetLecturerByID:input_type -> lecturer.GetLecturerByIDRequest
	5,  // 10: lecturer.LecturerService.GetLecturerByName:input_type -> lecturer.GetLecturerByNameRequest
	7,  // 11: lecturer.LecturerService.ListLecturers:input_type -> lecturer.ListLecturersRequest
	9,  // 12: lecturer.LecturerService.ListLecturersByFieldOfExpertise:input_type -> lecturer.ListLecturersByFieldOfExpertiseRequest
	14, // 13: lecturer.MailService.SendEmail:input_type -> lecturer.SendEmailRequest
	2,  // 14: lecturer.LecturerService.CreateLecturer:output_type -> lecturer.CreateLecturerResponse
	15, // 15: lecturer.LecturerService.UpdateLecturer:output_type -> google.protobuf.Empty
	13, // 16: lecturer.LecturerService.DeleteLecturer:output_type -> lecturer.DeleteLecturerResponse
	4,  // 17: lecturer.LecturerService.GetLecturerByID:output_type -> lecturer.GetLecturerByIDResponse
	6,  // 18: lecturer.LecturerService.GetLecturerByName:output_type -> lecturer.GetLecturerByNameResponse
	8,  // 19: lecturer.LecturerService.ListLecturers:output_type -> lecturer.ListLecturersResponse
	10, // 20: lecturer.LecturerService.ListLecturersByFieldOfExpertise:output_type -> lecturer.ListLecturersByFieldOfExpertiseResponse
	15, // 21: lecturer.MailService.SendEmail:output_type -> google.protobuf.Empty
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_lecturer_lecturer_proto_init() }
func file_proto_lecturer_lecturer_proto_init() {
	if File_proto_lecturer_lecturer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lecturer_lecturer_proto_rawDesc), len(file_proto_lecturer_lecturer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_lecturer_lecturer_proto_goTypes,
		DependencyIndexes: file_proto_lecturer_lecturer_proto_depIdxs,
		MessageInfos:      file_proto_lecturer_lecturer_proto_msgTypes,
	}.Build()
	File_proto_lecturer_lecturer_proto = out.File
	file_proto_lecturer_lecturer_proto_goTypes = nil
	file_proto_lecturer_lecturer_proto_depIdxs = nil
}
