// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lecturer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LecturerServiceClient is the client API for LecturerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LecturerServiceClient interface {
	// Create Lecturer
	CreateLecturer(ctx context.Context, in *CreateLecturerRequest, opts ...grpc.CallOption) (*CreateLecturerResponse, error)
	// Update Lecturer
	UpdateLecturer(ctx context.Context, in *UpdateLecturerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delete Lecturer
	DeleteLecturer(ctx context.Context, in *DeleteLecturerRequest, opts ...grpc.CallOption) (*DeleteLecturerResponse, error)
	// Get Lecturer by ID
	GetLecturerByID(ctx context.Context, in *GetLecturerByIDRequest, opts ...grpc.CallOption) (*GetLecturerByIDResponse, error)
	// Get lecturer by name
	GetLecturerByName(ctx context.Context, in *GetLecturerByNameRequest, opts ...grpc.CallOption) (*GetLecturerByNameResponse, error)
	// List lecturers
	ListLecturers(ctx context.Context, in *ListLecturersRequest, opts ...grpc.CallOption) (*ListLecturersResponse, error)
	// List lecturers by field of expertise
	ListLecturersByFieldOfExpertise(ctx context.Context, in *ListLecturersByFieldOfExpertiseRequest, opts ...grpc.CallOption) (*ListLecturersByFieldOfExpertiseResponse, error)
}

type lecturerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLecturerServiceClient(cc grpc.ClientConnInterface) LecturerServiceClient {
	return &lecturerServiceClient{cc}
}

func (c *lecturerServiceClient) CreateLecturer(ctx context.Context, in *CreateLecturerRequest, opts ...grpc.CallOption) (*CreateLecturerResponse, error) {
	out := new(CreateLecturerResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/CreateLecturer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) UpdateLecturer(ctx context.Context, in *UpdateLecturerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/UpdateLecturer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) DeleteLecturer(ctx context.Context, in *DeleteLecturerRequest, opts ...grpc.CallOption) (*DeleteLecturerResponse, error) {
	out := new(DeleteLecturerResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/DeleteLecturer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) GetLecturerByID(ctx context.Context, in *GetLecturerByIDRequest, opts ...grpc.CallOption) (*GetLecturerByIDResponse, error) {
	out := new(GetLecturerByIDResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/GetLecturerByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) GetLecturerByName(ctx context.Context, in *GetLecturerByNameRequest, opts ...grpc.CallOption) (*GetLecturerByNameResponse, error) {
	out := new(GetLecturerByNameResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/GetLecturerByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) ListLecturers(ctx context.Context, in *ListLecturersRequest, opts ...grpc.CallOption) (*ListLecturersResponse, error) {
	out := new(ListLecturersResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/ListLecturers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) ListLecturersByFieldOfExpertise(ctx context.Context, in *ListLecturersByFieldOfExpertiseRequest, opts ...grpc.CallOption) (*ListLecturersByFieldOfExpertiseResponse, error) {
	out := new(ListLecturersByFieldOfExpertiseResponse)
	err := c.cc.Invoke(ctx, "/lecturer.LecturerService/ListLecturersByFieldOfExpertise", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LecturerServiceServer is the server API for LecturerService service.
// All implementations must embed UnimplementedLecturerServiceServer
// for forward compatibility
type LecturerServiceServer interface {
	// Create Lecturer
	CreateLecturer(context.Context, *CreateLecturerRequest) (*CreateLecturerResponse, error)
	// Update Lecturer
	UpdateLecturer(context.Context, *UpdateLecturerRequest) (*emptypb.Empty, error)
	// Delete Lecturer
	DeleteLecturer(context.Context, *DeleteLecturerRequest) (*DeleteLecturerResponse, error)
	// Get Lecturer by ID
	GetLecturerByID(context.Context, *GetLecturerByIDRequest) (*GetLecturerByIDResponse, error)
	// Get lecturer by name
	GetLecturerByName(context.Context, *GetLecturerByNameRequest) (*GetLecturerByNameResponse, error)
	// List lecturers
	ListLecturers(context.Context, *ListLecturersRequest) (*ListLecturersResponse, error)
	// List lecturers by field of expertise
	ListLecturersByFieldOfExpertise(context.Context, *ListLecturersByFieldOfExpertiseRequest) (*ListLecturersByFieldOfExpertiseResponse, error)
	mustEmbedUnimplementedLecturerServiceServer()
}

// UnimplementedLecturerServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLecturerServiceServer struct {
}

func (UnimplementedLecturerServiceServer) CreateLecturer(context.Context, *CreateLecturerRequest) (*CreateLecturerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) UpdateLecturer(context.Context, *UpdateLecturerRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) DeleteLecturer(context.Context, *DeleteLecturerRequest) (*DeleteLecturerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) GetLecturerByID(context.Context, *GetLecturerByIDRequest) (*GetLecturerByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLecturerByID not implemented")
}
func (UnimplementedLecturerServiceServer) GetLecturerByName(context.Context, *GetLecturerByNameRequest) (*GetLecturerByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLecturerByName not implemented")
}
func (UnimplementedLecturerServiceServer) ListLecturers(context.Context, *ListLecturersRequest) (*ListLecturersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLecturers not implemented")
}
func (UnimplementedLecturerServiceServer) ListLecturersByFieldOfExpertise(context.Context, *ListLecturersByFieldOfExpertiseRequest) (*ListLecturersByFieldOfExpertiseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLecturersByFieldOfExpertise not implemented")
}
func (UnimplementedLecturerServiceServer) mustEmbedUnimplementedLecturerServiceServer() {}

// UnsafeLecturerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LecturerServiceServer will
// result in compilation errors.
type UnsafeLecturerServiceServer interface {
	mustEmbedUnimplementedLecturerServiceServer()
}

func RegisterLecturerServiceServer(s *grpc.Server, srv LecturerServiceServer) {
	s.RegisterService(&_LecturerService_serviceDesc, srv)
}

func _LecturerService_CreateLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).CreateLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/CreateLecturer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).CreateLecturer(ctx, req.(*CreateLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_UpdateLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).UpdateLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/UpdateLecturer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).UpdateLecturer(ctx, req.(*UpdateLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_DeleteLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).DeleteLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/DeleteLecturer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).DeleteLecturer(ctx, req.(*DeleteLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_GetLecturerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLecturerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).GetLecturerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/GetLecturerByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).GetLecturerByID(ctx, req.(*GetLecturerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_GetLecturerByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLecturerByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).GetLecturerByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/GetLecturerByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).GetLecturerByName(ctx, req.(*GetLecturerByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_ListLecturers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLecturersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).ListLecturers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/ListLecturers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).ListLecturers(ctx, req.(*ListLecturersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_ListLecturersByFieldOfExpertise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLecturersByFieldOfExpertiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).ListLecturersByFieldOfExpertise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecturer.LecturerService/ListLecturersByFieldOfExpertise",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).ListLecturersByFieldOfExpertise(ctx, req.(*ListLecturersByFieldOfExpertiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LecturerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lecturer.LecturerService",
	HandlerType: (*LecturerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLecturer",
			Handler:    _LecturerService_CreateLecturer_Handler,
		},
		{
			MethodName: "UpdateLecturer",
			Handler:    _LecturerService_UpdateLecturer_Handler,
		},
		{
			MethodName: "DeleteLecturer",
			Handler:    _LecturerService_DeleteLecturer_Handler,
		},
		{
			MethodName: "GetLecturerByID",
			Handler:    _LecturerService_GetLecturerByID_Handler,
		},
		{
			MethodName: "GetLecturerByName",
			Handler:    _LecturerService_GetLecturerByName_Handler,
		},
		{
			MethodName: "ListLecturers",
			Handler:    _LecturerService_ListLecturers_Handler,
		},
		{
			MethodName: "ListLecturersByFieldOfExpertise",
			Handler:    _LecturerService_ListLecturersByFieldOfExpertise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lecturer/lecturer.proto",
}
