// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/lecturer/lecturer.proto

package lecturer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LecturerService_CreateLecturer_FullMethodName                  = "/lecturer.LecturerService/CreateLecturer"
	LecturerService_UpdateLecturer_FullMethodName                  = "/lecturer.LecturerService/UpdateLecturer"
	LecturerService_DeleteLecturer_FullMethodName                  = "/lecturer.LecturerService/DeleteLecturer"
	LecturerService_GetLecturerByID_FullMethodName                 = "/lecturer.LecturerService/GetLecturerByID"
	LecturerService_GetLecturerByName_FullMethodName               = "/lecturer.LecturerService/GetLecturerByName"
	LecturerService_ListLecturers_FullMethodName                   = "/lecturer.LecturerService/ListLecturers"
	LecturerService_ListLecturersByFieldOfExpertise_FullMethodName = "/lecturer.LecturerService/ListLecturersByFieldOfExpertise"
)

// LecturerServiceClient is the client API for LecturerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LecturerServiceClient interface {
	// Create Lecturer
	CreateLecturer(ctx context.Context, in *CreateLecturerRequest, opts ...grpc.CallOption) (*CreateLecturerResponse, error)
	// Update Lecturer
	UpdateLecturer(ctx context.Context, in *UpdateLecturerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delete Lecturer
	DeleteLecturer(ctx context.Context, in *DeleteLecturerRequest, opts ...grpc.CallOption) (*DeleteLecturerResponse, error)
	// Get Lecturer by ID
	GetLecturerByID(ctx context.Context, in *GetLecturerByIDRequest, opts ...grpc.CallOption) (*GetLecturerByIDResponse, error)
	// Get lecturer by name
	GetLecturerByName(ctx context.Context, in *GetLecturerByNameRequest, opts ...grpc.CallOption) (*GetLecturerByNameResponse, error)
	// List lecturers
	ListLecturers(ctx context.Context, in *ListLecturersRequest, opts ...grpc.CallOption) (*ListLecturersResponse, error)
	// List lecturers by field of expertise
	ListLecturersByFieldOfExpertise(ctx context.Context, in *ListLecturersByFieldOfExpertiseRequest, opts ...grpc.CallOption) (*ListLecturersByFieldOfExpertiseResponse, error)
}

type lecturerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLecturerServiceClient(cc grpc.ClientConnInterface) LecturerServiceClient {
	return &lecturerServiceClient{cc}
}

func (c *lecturerServiceClient) CreateLecturer(ctx context.Context, in *CreateLecturerRequest, opts ...grpc.CallOption) (*CreateLecturerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLecturerResponse)
	err := c.cc.Invoke(ctx, LecturerService_CreateLecturer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) UpdateLecturer(ctx context.Context, in *UpdateLecturerRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, LecturerService_UpdateLecturer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) DeleteLecturer(ctx context.Context, in *DeleteLecturerRequest, opts ...grpc.CallOption) (*DeleteLecturerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLecturerResponse)
	err := c.cc.Invoke(ctx, LecturerService_DeleteLecturer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) GetLecturerByID(ctx context.Context, in *GetLecturerByIDRequest, opts ...grpc.CallOption) (*GetLecturerByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLecturerByIDResponse)
	err := c.cc.Invoke(ctx, LecturerService_GetLecturerByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) GetLecturerByName(ctx context.Context, in *GetLecturerByNameRequest, opts ...grpc.CallOption) (*GetLecturerByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLecturerByNameResponse)
	err := c.cc.Invoke(ctx, LecturerService_GetLecturerByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) ListLecturers(ctx context.Context, in *ListLecturersRequest, opts ...grpc.CallOption) (*ListLecturersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLecturersResponse)
	err := c.cc.Invoke(ctx, LecturerService_ListLecturers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lecturerServiceClient) ListLecturersByFieldOfExpertise(ctx context.Context, in *ListLecturersByFieldOfExpertiseRequest, opts ...grpc.CallOption) (*ListLecturersByFieldOfExpertiseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLecturersByFieldOfExpertiseResponse)
	err := c.cc.Invoke(ctx, LecturerService_ListLecturersByFieldOfExpertise_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LecturerServiceServer is the server API for LecturerService service.
// All implementations must embed UnimplementedLecturerServiceServer
// for forward compatibility.
type LecturerServiceServer interface {
	// Create Lecturer
	CreateLecturer(context.Context, *CreateLecturerRequest) (*CreateLecturerResponse, error)
	// Update Lecturer
	UpdateLecturer(context.Context, *UpdateLecturerRequest) (*emptypb.Empty, error)
	// Delete Lecturer
	DeleteLecturer(context.Context, *DeleteLecturerRequest) (*DeleteLecturerResponse, error)
	// Get Lecturer by ID
	GetLecturerByID(context.Context, *GetLecturerByIDRequest) (*GetLecturerByIDResponse, error)
	// Get lecturer by name
	GetLecturerByName(context.Context, *GetLecturerByNameRequest) (*GetLecturerByNameResponse, error)
	// List lecturers
	ListLecturers(context.Context, *ListLecturersRequest) (*ListLecturersResponse, error)
	// List lecturers by field of expertise
	ListLecturersByFieldOfExpertise(context.Context, *ListLecturersByFieldOfExpertiseRequest) (*ListLecturersByFieldOfExpertiseResponse, error)
	mustEmbedUnimplementedLecturerServiceServer()
}

// UnimplementedLecturerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLecturerServiceServer struct{}

func (UnimplementedLecturerServiceServer) CreateLecturer(context.Context, *CreateLecturerRequest) (*CreateLecturerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) UpdateLecturer(context.Context, *UpdateLecturerRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) DeleteLecturer(context.Context, *DeleteLecturerRequest) (*DeleteLecturerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLecturer not implemented")
}
func (UnimplementedLecturerServiceServer) GetLecturerByID(context.Context, *GetLecturerByIDRequest) (*GetLecturerByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLecturerByID not implemented")
}
func (UnimplementedLecturerServiceServer) GetLecturerByName(context.Context, *GetLecturerByNameRequest) (*GetLecturerByNameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLecturerByName not implemented")
}
func (UnimplementedLecturerServiceServer) ListLecturers(context.Context, *ListLecturersRequest) (*ListLecturersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLecturers not implemented")
}
func (UnimplementedLecturerServiceServer) ListLecturersByFieldOfExpertise(context.Context, *ListLecturersByFieldOfExpertiseRequest) (*ListLecturersByFieldOfExpertiseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLecturersByFieldOfExpertise not implemented")
}
func (UnimplementedLecturerServiceServer) mustEmbedUnimplementedLecturerServiceServer() {}
func (UnimplementedLecturerServiceServer) testEmbeddedByValue()                         {}

// UnsafeLecturerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LecturerServiceServer will
// result in compilation errors.
type UnsafeLecturerServiceServer interface {
	mustEmbedUnimplementedLecturerServiceServer()
}

func RegisterLecturerServiceServer(s grpc.ServiceRegistrar, srv LecturerServiceServer) {
	// If the following call panics, it indicates UnimplementedLecturerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LecturerService_ServiceDesc, srv)
}

func _LecturerService_CreateLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).CreateLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LecturerService_CreateLecturer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).CreateLecturer(ctx, req.(*CreateLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_UpdateLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).UpdateLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LecturerService_UpdateLecturer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).UpdateLecturer(ctx, req.(*UpdateLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_DeleteLecturer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLecturerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).DeleteLecturer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LecturerService_DeleteLecturer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).DeleteLecturer(ctx, req.(*DeleteLecturerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_GetLecturerByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLecturerByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).GetLecturerByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LecturerService_GetLecturerByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).GetLecturerByID(ctx, req.(*GetLecturerByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_GetLecturerByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLecturerByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).GetLecturerByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LecturerService_GetLecturerByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).GetLecturerByName(ctx, req.(*GetLecturerByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_ListLecturers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLecturersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).ListLecturers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LecturerService_ListLecturers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).ListLecturers(ctx, req.(*ListLecturersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LecturerService_ListLecturersByFieldOfExpertise_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLecturersByFieldOfExpertiseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LecturerServiceServer).ListLecturersByFieldOfExpertise(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LecturerService_ListLecturersByFieldOfExpertise_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LecturerServiceServer).ListLecturersByFieldOfExpertise(ctx, req.(*ListLecturersByFieldOfExpertiseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LecturerService_ServiceDesc is the grpc.ServiceDesc for LecturerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LecturerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lecturer.LecturerService",
	HandlerType: (*LecturerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLecturer",
			Handler:    _LecturerService_CreateLecturer_Handler,
		},
		{
			MethodName: "UpdateLecturer",
			Handler:    _LecturerService_UpdateLecturer_Handler,
		},
		{
			MethodName: "DeleteLecturer",
			Handler:    _LecturerService_DeleteLecturer_Handler,
		},
		{
			MethodName: "GetLecturerByID",
			Handler:    _LecturerService_GetLecturerByID_Handler,
		},
		{
			MethodName: "GetLecturerByName",
			Handler:    _LecturerService_GetLecturerByName_Handler,
		},
		{
			MethodName: "ListLecturers",
			Handler:    _LecturerService_ListLecturers_Handler,
		},
		{
			MethodName: "ListLecturersByFieldOfExpertise",
			Handler:    _LecturerService_ListLecturersByFieldOfExpertise_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lecturer/lecturer.proto",
}

const (
	MailService_SendEmail_FullMethodName = "/lecturer.MailService/SendEmail"
)

// MailServiceClient is the client API for MailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MailServiceClient interface {
	SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type mailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMailServiceClient(cc grpc.ClientConnInterface) MailServiceClient {
	return &mailServiceClient{cc}
}

func (c *mailServiceClient) SendEmail(ctx context.Context, in *SendEmailRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, MailService_SendEmail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MailServiceServer is the server API for MailService service.
// All implementations must embed UnimplementedMailServiceServer
// for forward compatibility.
type MailServiceServer interface {
	SendEmail(context.Context, *SendEmailRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedMailServiceServer()
}

// UnimplementedMailServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMailServiceServer struct{}

func (UnimplementedMailServiceServer) SendEmail(context.Context, *SendEmailRequest) (*emptypb.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method SendEmail not implemented")
}
func (UnimplementedMailServiceServer) mustEmbedUnimplementedMailServiceServer() {}
func (UnimplementedMailServiceServer) testEmbeddedByValue()                     {}

// UnsafeMailServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MailServiceServer will
// result in compilation errors.
type UnsafeMailServiceServer interface {
	mustEmbedUnimplementedMailServiceServer()
}

func RegisterMailServiceServer(s grpc.ServiceRegistrar, srv MailServiceServer) {
	// If the following call panics, it indicates UnimplementedMailServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MailService_ServiceDesc, srv)
}

func _MailService_SendEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendEmailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MailServiceServer).SendEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MailService_SendEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MailServiceServer).SendEmail(ctx, req.(*SendEmailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MailService_ServiceDesc is the grpc.ServiceDesc for MailService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MailService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lecturer.MailService",
	HandlerType: (*MailServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendEmail",
			Handler:    _MailService_SendEmail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lecturer/lecturer.proto",
}
