// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: proto/lecturer/lecturer.proto

package lecturer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lecturer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *Lecturer) Reset() {
	*x = Lecturer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lecturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lecturer) ProtoMessage() {}

func (x *Lecturer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lecturer.ProtoReflect.Descriptor instead.
func (*Lecturer) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{0}
}

func (x *Lecturer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lecturer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Lecturer) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lecturer) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type CreateLecturerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName         string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,3,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *CreateLecturerRequest) Reset() {
	*x = CreateLecturerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLecturerRequest) ProtoMessage() {}

func (x *CreateLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLecturerRequest.ProtoReflect.Descriptor instead.
func (*CreateLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLecturerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateLecturerRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLecturerRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type CreateLecturerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *CreateLecturerResponse) Reset() {
	*x = CreateLecturerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLecturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLecturerResponse) ProtoMessage() {}

func (x *CreateLecturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLecturerResponse.ProtoReflect.Descriptor instead.
func (*CreateLecturerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLecturerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateLecturerResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateLecturerResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLecturerResponse) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type GetLecturerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
}

func (x *GetLecturerRequest) Reset() {
	*x = GetLecturerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerRequest) ProtoMessage() {}

func (x *GetLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerRequest.ProtoReflect.Descriptor instead.
func (*GetLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{3}
}

func (x *GetLecturerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetLecturersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchCriteria string `protobuf:"bytes,1,opt,name=search_criteria,json=searchCriteria,proto3" json:"search_criteria,omitempty"`
}

func (x *GetLecturersRequest) Reset() {
	*x = GetLecturersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLecturersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturersRequest) ProtoMessage() {}

func (x *GetLecturersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturersRequest.ProtoReflect.Descriptor instead.
func (*GetLecturersRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{4}
}

func (x *GetLecturersRequest) GetSearchCriteria() string {
	if x != nil {
		return x.SearchCriteria
	}
	return ""
}

type UpdateLecturerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *UpdateLecturerRequest) Reset() {
	*x = UpdateLecturerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLecturerRequest) ProtoMessage() {}

func (x *UpdateLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLecturerRequest.ProtoReflect.Descriptor instead.
func (*UpdateLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLecturerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLecturerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateLecturerRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLecturerRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type GetLecturerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *GetLecturerResponse) Reset() {
	*x = GetLecturerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLecturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerResponse) ProtoMessage() {}

func (x *GetLecturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerResponse.ProtoReflect.Descriptor instead.
func (*GetLecturerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{6}
}

func (x *GetLecturerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetLecturerResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *GetLecturerResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetLecturerResponse) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type DeleteLecturerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteLecturerRequest) Reset() {
	*x = DeleteLecturerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLecturerRequest) ProtoMessage() {}

func (x *DeleteLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLecturerRequest.ProtoReflect.Descriptor instead.
func (*DeleteLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLecturerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLecturerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *DeleteLecturerResponse) Reset() {
	*x = DeleteLecturerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLecturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLecturerResponse) ProtoMessage() {}

func (x *DeleteLecturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLecturerResponse.ProtoReflect.Descriptor instead.
func (*DeleteLecturerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteLecturerResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteLecturerResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DeleteLecturerResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *DeleteLecturerResponse) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

var File_proto_lecturer_lecturer_proto protoreflect.FileDescriptor

var file_proto_lecturer_lecturer_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x2f, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x08, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f,
	0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x22, 0x78, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x22, 0x89, 0x01,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66,
	0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x22, 0x31, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3e, 0x0a, 0x13,
	0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x5f, 0x63, 0x72,
	0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x73, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x43, 0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x22, 0x88, 0x01, 0x0a,
	0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65,
	0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x22, 0x27, 0x0a, 0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x89, 0x01, 0x0a, 0x16, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x32, 0xb2, 0x03, 0x0a, 0x0f, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x52, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x12, 0x55, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x50, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x12, 0x1d, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x30, 0x01, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x75, 0x6b, 0x61, 0x44, 0x65, 0x72,
	0x76, 0x69, 0x73, 0x65, 0x76, 0x69, 0x63, 0x2f, 0x4d, 0x69, 0x6b, 0x72, 0x6f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x73, 0x6e, 0x61, 0x41, 0x72, 0x68, 0x69, 0x74, 0x65, 0x6b, 0x74, 0x75, 0x72, 0x61,
	0x49, 0x53, 0x50, 0x72, 0x6f, 0x6a, 0x65, 0x6b, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_lecturer_lecturer_proto_rawDescOnce sync.Once
	file_proto_lecturer_lecturer_proto_rawDescData = file_proto_lecturer_lecturer_proto_rawDesc
)

func file_proto_lecturer_lecturer_proto_rawDescGZIP() []byte {
	file_proto_lecturer_lecturer_proto_rawDescOnce.Do(func() {
		file_proto_lecturer_lecturer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lecturer_lecturer_proto_rawDescData)
	})
	return file_proto_lecturer_lecturer_proto_rawDescData
}

var file_proto_lecturer_lecturer_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_lecturer_lecturer_proto_goTypes = []interface{}{
	(*Lecturer)(nil),               // 0: lecturer.Lecturer
	(*CreateLecturerRequest)(nil),  // 1: lecturer.CreateLecturerRequest
	(*CreateLecturerResponse)(nil), // 2: lecturer.CreateLecturerResponse
	(*GetLecturerRequest)(nil),     // 3: lecturer.GetLecturerRequest
	(*GetLecturersRequest)(nil),    // 4: lecturer.GetLecturersRequest
	(*UpdateLecturerRequest)(nil),  // 5: lecturer.UpdateLecturerRequest
	(*GetLecturerResponse)(nil),    // 6: lecturer.GetLecturerResponse
	(*DeleteLecturerRequest)(nil),  // 7: lecturer.DeleteLecturerRequest
	(*DeleteLecturerResponse)(nil), // 8: lecturer.DeleteLecturerResponse
	(*emptypb.Empty)(nil),          // 9: google.protobuf.Empty
}
var file_proto_lecturer_lecturer_proto_depIdxs = []int32{
	1, // 0: lecturer.LecturerService.CreateLecturer:input_type -> lecturer.CreateLecturerRequest
	3, // 1: lecturer.LecturerService.GetLecturerByName:input_type -> lecturer.GetLecturerRequest
	5, // 2: lecturer.LecturerService.UpdateLecturer:input_type -> lecturer.UpdateLecturerRequest
	7, // 3: lecturer.LecturerService.DeleteLecturer:input_type -> lecturer.DeleteLecturerRequest
	4, // 4: lecturer.LecturerService.GetLecturers:input_type -> lecturer.GetLecturersRequest
	2, // 5: lecturer.LecturerService.CreateLecturer:output_type -> lecturer.CreateLecturerResponse
	6, // 6: lecturer.LecturerService.GetLecturerByName:output_type -> lecturer.GetLecturerResponse
	9, // 7: lecturer.LecturerService.UpdateLecturer:output_type -> google.protobuf.Empty
	8, // 8: lecturer.LecturerService.DeleteLecturer:output_type -> lecturer.DeleteLecturerResponse
	6, // 9: lecturer.LecturerService.GetLecturers:output_type -> lecturer.GetLecturerResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_lecturer_lecturer_proto_init() }
func file_proto_lecturer_lecturer_proto_init() {
	if File_proto_lecturer_lecturer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lecturer_lecturer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lecturer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLecturerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLecturerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLecturerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLecturersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLecturerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLecturerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLecturerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLecturerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lecturer_lecturer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lecturer_lecturer_proto_goTypes,
		DependencyIndexes: file_proto_lecturer_lecturer_proto_depIdxs,
		MessageInfos:      file_proto_lecturer_lecturer_proto_msgTypes,
	}.Build()
	File_proto_lecturer_lecturer_proto = out.File
	file_proto_lecturer_lecturer_proto_rawDesc = nil
	file_proto_lecturer_lecturer_proto_goTypes = nil
	file_proto_lecturer_lecturer_proto_depIdxs = nil
}
