// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v3.21.12
// source: proto/lecturer/lecturer.proto

package lecturer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lecturer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *Lecturer) Reset() {
	*x = Lecturer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Lecturer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lecturer) ProtoMessage() {}

func (x *Lecturer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lecturer.ProtoReflect.Descriptor instead.
func (*Lecturer) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{0}
}

func (x *Lecturer) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lecturer) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *Lecturer) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Lecturer) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type CreateLecturerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName         string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,3,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *CreateLecturerRequest) Reset() {
	*x = CreateLecturerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLecturerRequest) ProtoMessage() {}

func (x *CreateLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLecturerRequest.ProtoReflect.Descriptor instead.
func (*CreateLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLecturerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateLecturerRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLecturerRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type CreateLecturerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lecturer *Lecturer `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
}

func (x *CreateLecturerResponse) Reset() {
	*x = CreateLecturerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateLecturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLecturerResponse) ProtoMessage() {}

func (x *CreateLecturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLecturerResponse.ProtoReflect.Descriptor instead.
func (*CreateLecturerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLecturerResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

type GetLecturerByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetLecturerByIDRequest) Reset() {
	*x = GetLecturerByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLecturerByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByIDRequest) ProtoMessage() {}

func (x *GetLecturerByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLecturerByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{3}
}

func (x *GetLecturerByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLecturerByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lecturer *Lecturer `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
}

func (x *GetLecturerByIDResponse) Reset() {
	*x = GetLecturerByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLecturerByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByIDResponse) ProtoMessage() {}

func (x *GetLecturerByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByIDResponse.ProtoReflect.Descriptor instead.
func (*GetLecturerByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{4}
}

func (x *GetLecturerByIDResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

type GetLecturerByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FullName string `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
}

func (x *GetLecturerByNameRequest) Reset() {
	*x = GetLecturerByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLecturerByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByNameRequest) ProtoMessage() {}

func (x *GetLecturerByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByNameRequest.ProtoReflect.Descriptor instead.
func (*GetLecturerByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{5}
}

func (x *GetLecturerByNameRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

type GetLecturerByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lecturer *Lecturer `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
}

func (x *GetLecturerByNameResponse) Reset() {
	*x = GetLecturerByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLecturerByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLecturerByNameResponse) ProtoMessage() {}

func (x *GetLecturerByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLecturerByNameResponse.ProtoReflect.Descriptor instead.
func (*GetLecturerByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{6}
}

func (x *GetLecturerByNameResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

type ListLecturersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page             int32  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,3,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
	Title            string `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
}

func (x *ListLecturersRequest) Reset() {
	*x = ListLecturersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLecturersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersRequest) ProtoMessage() {}

func (x *ListLecturersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersRequest.ProtoReflect.Descriptor instead.
func (*ListLecturersRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{7}
}

func (x *ListLecturersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturersRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

func (x *ListLecturersRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListLecturersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lecturers   []*Lecturer `protobuf:"bytes,1,rep,name=lecturers,proto3" json:"lecturers,omitempty"`
	TotalCount  int32       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page        int32       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize    int32       `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasNextPage bool        `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
}

func (x *ListLecturersResponse) Reset() {
	*x = ListLecturersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLecturersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersResponse) ProtoMessage() {}

func (x *ListLecturersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersResponse.ProtoReflect.Descriptor instead.
func (*ListLecturersResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{8}
}

func (x *ListLecturersResponse) GetLecturers() []*Lecturer {
	if x != nil {
		return x.Lecturers
	}
	return nil
}

func (x *ListLecturersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListLecturersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturersResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type ListLecturersByFieldOfExpertiseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldOfExpertise string `protobuf:"bytes,1,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
	Page             int32  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize         int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListLecturersByFieldOfExpertiseRequest) Reset() {
	*x = ListLecturersByFieldOfExpertiseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLecturersByFieldOfExpertiseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersByFieldOfExpertiseRequest) ProtoMessage() {}

func (x *ListLecturersByFieldOfExpertiseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersByFieldOfExpertiseRequest.ProtoReflect.Descriptor instead.
func (*ListLecturersByFieldOfExpertiseRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{9}
}

func (x *ListLecturersByFieldOfExpertiseRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

func (x *ListLecturersByFieldOfExpertiseRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLecturersByFieldOfExpertiseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lecturers   []*Lecturer `protobuf:"bytes,1,rep,name=lecturers,proto3" json:"lecturers,omitempty"`
	TotalCount  int32       `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page        int32       `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize    int32       `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasNextPage bool        `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
}

func (x *ListLecturersByFieldOfExpertiseResponse) Reset() {
	*x = ListLecturersByFieldOfExpertiseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListLecturersByFieldOfExpertiseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturersByFieldOfExpertiseResponse) ProtoMessage() {}

func (x *ListLecturersByFieldOfExpertiseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturersByFieldOfExpertiseResponse.ProtoReflect.Descriptor instead.
func (*ListLecturersByFieldOfExpertiseResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{10}
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetLecturers() []*Lecturer {
	if x != nil {
		return x.Lecturers
	}
	return nil
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturersByFieldOfExpertiseResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type UpdateLecturerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id               int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName         string `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Title            string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	FieldOfExpertise string `protobuf:"bytes,4,opt,name=field_of_expertise,json=fieldOfExpertise,proto3" json:"field_of_expertise,omitempty"`
}

func (x *UpdateLecturerRequest) Reset() {
	*x = UpdateLecturerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLecturerRequest) ProtoMessage() {}

func (x *UpdateLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLecturerRequest.ProtoReflect.Descriptor instead.
func (*UpdateLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateLecturerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLecturerRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UpdateLecturerRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateLecturerRequest) GetFieldOfExpertise() string {
	if x != nil {
		return x.FieldOfExpertise
	}
	return ""
}

type DeleteLecturerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteLecturerRequest) Reset() {
	*x = DeleteLecturerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLecturerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLecturerRequest) ProtoMessage() {}

func (x *DeleteLecturerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLecturerRequest.ProtoReflect.Descriptor instead.
func (*DeleteLecturerRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteLecturerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLecturerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lecturer *Lecturer `protobuf:"bytes,1,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
}

func (x *DeleteLecturerResponse) Reset() {
	*x = DeleteLecturerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_lecturer_lecturer_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteLecturerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLecturerResponse) ProtoMessage() {}

func (x *DeleteLecturerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecturer_lecturer_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLecturerResponse.ProtoReflect.Descriptor instead.
func (*DeleteLecturerResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecturer_lecturer_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteLecturerResponse) GetLecturer() *Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

var File_proto_lecturer_lecturer_proto protoreflect.FileDescriptor

var file_proto_lecturer_lecturer_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x2f, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x7b, 0x0a, 0x08, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f,
	0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x22, 0x78, 0x0a, 0x15, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09,
	0x66, 0x75, 0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x66, 0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74,
	0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12,
	0x2c, 0x0a, 0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65,
	0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x22, 0x48, 0x0a,
	0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x65, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x08, 0x6c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x22, 0x28, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x4c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69,
	0x64, 0x22, 0x49, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08,
	0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12,
	0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x52, 0x08, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x22, 0x37, 0x0a, 0x18,
	0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75, 0x6c, 0x6c,
	0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x75, 0x6c,
	0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4b, 0x0a, 0x19, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x08, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e,
	0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x08, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x22, 0x8b, 0x01, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x2c, 0x0a, 0x12,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x22, 0xbf, 0x01, 0x0a, 0x15, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x72, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x6c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x72, 0x52, 0x09, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b,
	0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22,
	0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x50, 0x61,
	0x67, 0x65, 0x22, 0x87, 0x01, 0x0a, 0x26, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x73, 0x42, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70,
	0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a,
	0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0xd1, 0x01, 0x0a,
	0x27, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x42, 0x79,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x09, 0x6c, 0x65, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x6c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52,
	0x09, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x22, 0x0a, 0x0d,
	0x68, 0x61, 0x73, 0x5f, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x70, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0b, 0x68, 0x61, 0x73, 0x4e, 0x65, 0x78, 0x74, 0x50, 0x61, 0x67, 0x65,
	0x22, 0x88, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x75,
	0x6c, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x75, 0x6c, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x2c, 0x0a,
	0x12, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x6f, 0x66, 0x5f, 0x65, 0x78, 0x70, 0x65, 0x72, 0x74,
	0x69, 0x73, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x66, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x48, 0x0a, 0x16, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2e,
	0x0a, 0x08, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x4c, 0x65, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x52, 0x08, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x32, 0xa5,
	0x05, 0x0a, 0x0f, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x55, 0x0a, 0x0e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x4b, 0x0a, 0x0e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x12, 0x1f, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x6c, 0x65, 0x63, 0x74,
	0x75, 0x72, 0x65, 0x72, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x0f, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44,
	0x12, 0x20, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x21, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x4c, 0x65,
	0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x22, 0x2e, 0x6c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x23, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x4c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x52, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x12, 0x1e, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75,
	0x72, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x88, 0x01, 0x0a, 0x1f,
	0x4c, 0x69, 0x73, 0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x42, 0x79, 0x46,
	0x69, 0x65, 0x6c, 0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x12,
	0x30, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x4c,
	0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x42, 0x79, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f,
	0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x31, 0x2e, 0x6c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x4c, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65, 0x72, 0x73, 0x42, 0x79, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x66, 0x45, 0x78, 0x70, 0x65, 0x72, 0x74, 0x69, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4d, 0x5a, 0x4b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4c, 0x75, 0x6b, 0x61, 0x44, 0x65, 0x72, 0x76, 0x69, 0x73, 0x65,
	0x76, 0x69, 0x63, 0x2f, 0x4d, 0x69, 0x6b, 0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x73, 0x6e,
	0x61, 0x41, 0x72, 0x68, 0x69, 0x74, 0x65, 0x6b, 0x74, 0x75, 0x72, 0x61, 0x49, 0x53, 0x50, 0x72,
	0x6f, 0x6a, 0x65, 0x6b, 0x61, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_lecturer_lecturer_proto_rawDescOnce sync.Once
	file_proto_lecturer_lecturer_proto_rawDescData = file_proto_lecturer_lecturer_proto_rawDesc
)

func file_proto_lecturer_lecturer_proto_rawDescGZIP() []byte {
	file_proto_lecturer_lecturer_proto_rawDescOnce.Do(func() {
		file_proto_lecturer_lecturer_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_lecturer_lecturer_proto_rawDescData)
	})
	return file_proto_lecturer_lecturer_proto_rawDescData
}

var file_proto_lecturer_lecturer_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_lecturer_lecturer_proto_goTypes = []interface{}{
	(*Lecturer)(nil),                                // 0: lecturer.Lecturer
	(*CreateLecturerRequest)(nil),                   // 1: lecturer.CreateLecturerRequest
	(*CreateLecturerResponse)(nil),                  // 2: lecturer.CreateLecturerResponse
	(*GetLecturerByIDRequest)(nil),                  // 3: lecturer.GetLecturerByIDRequest
	(*GetLecturerByIDResponse)(nil),                 // 4: lecturer.GetLecturerByIDResponse
	(*GetLecturerByNameRequest)(nil),                // 5: lecturer.GetLecturerByNameRequest
	(*GetLecturerByNameResponse)(nil),               // 6: lecturer.GetLecturerByNameResponse
	(*ListLecturersRequest)(nil),                    // 7: lecturer.ListLecturersRequest
	(*ListLecturersResponse)(nil),                   // 8: lecturer.ListLecturersResponse
	(*ListLecturersByFieldOfExpertiseRequest)(nil),  // 9: lecturer.ListLecturersByFieldOfExpertiseRequest
	(*ListLecturersByFieldOfExpertiseResponse)(nil), // 10: lecturer.ListLecturersByFieldOfExpertiseResponse
	(*UpdateLecturerRequest)(nil),                   // 11: lecturer.UpdateLecturerRequest
	(*DeleteLecturerRequest)(nil),                   // 12: lecturer.DeleteLecturerRequest
	(*DeleteLecturerResponse)(nil),                  // 13: lecturer.DeleteLecturerResponse
	(*emptypb.Empty)(nil),                           // 14: google.protobuf.Empty
}
var file_proto_lecturer_lecturer_proto_depIdxs = []int32{
	0,  // 0: lecturer.CreateLecturerResponse.lecturer:type_name -> lecturer.Lecturer
	0,  // 1: lecturer.GetLecturerByIDResponse.lecturer:type_name -> lecturer.Lecturer
	0,  // 2: lecturer.GetLecturerByNameResponse.lecturer:type_name -> lecturer.Lecturer
	0,  // 3: lecturer.ListLecturersResponse.lecturers:type_name -> lecturer.Lecturer
	0,  // 4: lecturer.ListLecturersByFieldOfExpertiseResponse.lecturers:type_name -> lecturer.Lecturer
	0,  // 5: lecturer.DeleteLecturerResponse.lecturer:type_name -> lecturer.Lecturer
	1,  // 6: lecturer.LecturerService.CreateLecturer:input_type -> lecturer.CreateLecturerRequest
	11, // 7: lecturer.LecturerService.UpdateLecturer:input_type -> lecturer.UpdateLecturerRequest
	12, // 8: lecturer.LecturerService.DeleteLecturer:input_type -> lecturer.DeleteLecturerRequest
	3,  // 9: lecturer.LecturerService.GetLecturerByID:input_type -> lecturer.GetLecturerByIDRequest
	5,  // 10: lecturer.LecturerService.GetLecturerByName:input_type -> lecturer.GetLecturerByNameRequest
	7,  // 11: lecturer.LecturerService.ListLecturers:input_type -> lecturer.ListLecturersRequest
	9,  // 12: lecturer.LecturerService.ListLecturersByFieldOfExpertise:input_type -> lecturer.ListLecturersByFieldOfExpertiseRequest
	2,  // 13: lecturer.LecturerService.CreateLecturer:output_type -> lecturer.CreateLecturerResponse
	14, // 14: lecturer.LecturerService.UpdateLecturer:output_type -> google.protobuf.Empty
	13, // 15: lecturer.LecturerService.DeleteLecturer:output_type -> lecturer.DeleteLecturerResponse
	4,  // 16: lecturer.LecturerService.GetLecturerByID:output_type -> lecturer.GetLecturerByIDResponse
	6,  // 17: lecturer.LecturerService.GetLecturerByName:output_type -> lecturer.GetLecturerByNameResponse
	8,  // 18: lecturer.LecturerService.ListLecturers:output_type -> lecturer.ListLecturersResponse
	10, // 19: lecturer.LecturerService.ListLecturersByFieldOfExpertise:output_type -> lecturer.ListLecturersByFieldOfExpertiseResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_lecturer_lecturer_proto_init() }
func file_proto_lecturer_lecturer_proto_init() {
	if File_proto_lecturer_lecturer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_lecturer_lecturer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Lecturer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLecturerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateLecturerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLecturerByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLecturerByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLecturerByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetLecturerByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLecturersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLecturersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLecturersByFieldOfExpertiseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListLecturersByFieldOfExpertiseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLecturerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLecturerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_lecturer_lecturer_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteLecturerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_lecturer_lecturer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lecturer_lecturer_proto_goTypes,
		DependencyIndexes: file_proto_lecturer_lecturer_proto_depIdxs,
		MessageInfos:      file_proto_lecturer_lecturer_proto_msgTypes,
	}.Build()
	File_proto_lecturer_lecturer_proto = out.File
	file_proto_lecturer_lecturer_proto_rawDesc = nil
	file_proto_lecturer_lecturer_proto_goTypes = nil
	file_proto_lecturer_lecturer_proto_depIdxs = nil
}
