// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/lecture/lecture.proto

package lecture

import (
	event "github.com/LukaDervisevic/MikroservisnaArhitekturaISProjekat/proto/event"
	lecturer "github.com/LukaDervisevic/MikroservisnaArhitekturaISProjekat/proto/lecturer"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Lecture struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Lecturer      *lecturer.Lecturer     `protobuf:"bytes,2,opt,name=lecturer,proto3" json:"lecturer,omitempty"`
	Event         *event.Event           `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Lecture) Reset() {
	*x = Lecture{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Lecture) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Lecture) ProtoMessage() {}

func (x *Lecture) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Lecture.ProtoReflect.Descriptor instead.
func (*Lecture) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{0}
}

func (x *Lecture) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Lecture) GetLecturer() *lecturer.Lecturer {
	if x != nil {
		return x.Lecturer
	}
	return nil
}

func (x *Lecture) GetEvent() *event.Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *Lecture) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Lecture) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type LectureQuery struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	LectureId                int64                  `protobuf:"varint,1,opt,name=lecture_id,json=lectureId,proto3" json:"lecture_id,omitempty"`
	LecturerId               int64                  `protobuf:"varint,2,opt,name=lecturer_id,json=lecturerId,proto3" json:"lecturer_id,omitempty"`
	LecturerFullName         string                 `protobuf:"bytes,3,opt,name=lecturer_full_name,json=lecturerFullName,proto3" json:"lecturer_full_name,omitempty"`
	LecturerTitle            string                 `protobuf:"bytes,4,opt,name=lecturer_title,json=lecturerTitle,proto3" json:"lecturer_title,omitempty"`
	LecturerFieldOfExpertise string                 `protobuf:"bytes,5,opt,name=lecturer_field_of_expertise,json=lecturerFieldOfExpertise,proto3" json:"lecturer_field_of_expertise,omitempty"`
	EventId                  int64                  `protobuf:"varint,6,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventName                string                 `protobuf:"bytes,7,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventCotisationPrice     float64                `protobuf:"fixed64,8,opt,name=event_cotisation_price,json=eventCotisationPrice,proto3" json:"event_cotisation_price,omitempty"`
	EventAgenda              string                 `protobuf:"bytes,9,opt,name=event_agenda,json=eventAgenda,proto3" json:"event_agenda,omitempty"`
	EventType                string                 `protobuf:"bytes,10,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventDateTime            *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=event_date_time,json=eventDateTime,proto3" json:"event_date_time,omitempty"`
	LocationId               int64                  `protobuf:"varint,12,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	LocationName             string                 `protobuf:"bytes,13,opt,name=location_name,json=locationName,proto3" json:"location_name,omitempty"`
	LocationAddress          string                 `protobuf:"bytes,14,opt,name=location_address,json=locationAddress,proto3" json:"location_address,omitempty"`
	LocationCapacity         int64                  `protobuf:"varint,15,opt,name=location_capacity,json=locationCapacity,proto3" json:"location_capacity,omitempty"`
	LectureName              string                 `protobuf:"bytes,16,opt,name=lecture_name,json=lectureName,proto3" json:"lecture_name,omitempty"`
	LectureDuration          *durationpb.Duration   `protobuf:"bytes,17,opt,name=lecture_duration,json=lectureDuration,proto3" json:"lecture_duration,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *LectureQuery) Reset() {
	*x = LectureQuery{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LectureQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LectureQuery) ProtoMessage() {}

func (x *LectureQuery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LectureQuery.ProtoReflect.Descriptor instead.
func (*LectureQuery) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{1}
}

func (x *LectureQuery) GetLectureId() int64 {
	if x != nil {
		return x.LectureId
	}
	return 0
}

func (x *LectureQuery) GetLecturerId() int64 {
	if x != nil {
		return x.LecturerId
	}
	return 0
}

func (x *LectureQuery) GetLecturerFullName() string {
	if x != nil {
		return x.LecturerFullName
	}
	return ""
}

func (x *LectureQuery) GetLecturerTitle() string {
	if x != nil {
		return x.LecturerTitle
	}
	return ""
}

func (x *LectureQuery) GetLecturerFieldOfExpertise() string {
	if x != nil {
		return x.LecturerFieldOfExpertise
	}
	return ""
}

func (x *LectureQuery) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *LectureQuery) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *LectureQuery) GetEventCotisationPrice() float64 {
	if x != nil {
		return x.EventCotisationPrice
	}
	return 0
}

func (x *LectureQuery) GetEventAgenda() string {
	if x != nil {
		return x.EventAgenda
	}
	return ""
}

func (x *LectureQuery) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *LectureQuery) GetEventDateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EventDateTime
	}
	return nil
}

func (x *LectureQuery) GetLocationId() int64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *LectureQuery) GetLocationName() string {
	if x != nil {
		return x.LocationName
	}
	return ""
}

func (x *LectureQuery) GetLocationAddress() string {
	if x != nil {
		return x.LocationAddress
	}
	return ""
}

func (x *LectureQuery) GetLocationCapacity() int64 {
	if x != nil {
		return x.LocationCapacity
	}
	return 0
}

func (x *LectureQuery) GetLectureName() string {
	if x != nil {
		return x.LectureName
	}
	return ""
}

func (x *LectureQuery) GetLectureDuration() *durationpb.Duration {
	if x != nil {
		return x.LectureDuration
	}
	return nil
}

type CreateLectureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LecturerId    int64                  `protobuf:"varint,1,opt,name=lecturer_id,json=lecturerId,proto3" json:"lecturer_id,omitempty"`
	EventId       int64                  `protobuf:"varint,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLectureRequest) Reset() {
	*x = CreateLectureRequest{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLectureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLectureRequest) ProtoMessage() {}

func (x *CreateLectureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLectureRequest.ProtoReflect.Descriptor instead.
func (*CreateLectureRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{2}
}

func (x *CreateLectureRequest) GetLecturerId() int64 {
	if x != nil {
		return x.LecturerId
	}
	return 0
}

func (x *CreateLectureRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *CreateLectureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLectureRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type CreateLectureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecture       *Lecture               `protobuf:"bytes,1,opt,name=lecture,proto3" json:"lecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLectureResponse) Reset() {
	*x = CreateLectureResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLectureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLectureResponse) ProtoMessage() {}

func (x *CreateLectureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLectureResponse.ProtoReflect.Descriptor instead.
func (*CreateLectureResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLectureResponse) GetLecture() *Lecture {
	if x != nil {
		return x.Lecture
	}
	return nil
}

type GetLectureByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLectureByIDRequest) Reset() {
	*x = GetLectureByIDRequest{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureByIDRequest) ProtoMessage() {}

func (x *GetLectureByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureByIDRequest.ProtoReflect.Descriptor instead.
func (*GetLectureByIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{4}
}

func (x *GetLectureByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetLectureByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecture       *Lecture               `protobuf:"bytes,1,opt,name=lecture,proto3" json:"lecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLectureByIDResponse) Reset() {
	*x = GetLectureByIDResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureByIDResponse) ProtoMessage() {}

func (x *GetLectureByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureByIDResponse.ProtoReflect.Descriptor instead.
func (*GetLectureByIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{5}
}

func (x *GetLectureByIDResponse) GetLecture() *Lecture {
	if x != nil {
		return x.Lecture
	}
	return nil
}

type GetLectureByNameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLectureByNameRequest) Reset() {
	*x = GetLectureByNameRequest{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureByNameRequest) ProtoMessage() {}

func (x *GetLectureByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureByNameRequest.ProtoReflect.Descriptor instead.
func (*GetLectureByNameRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{6}
}

func (x *GetLectureByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetLectureByNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecture       *Lecture               `protobuf:"bytes,1,opt,name=lecture,proto3" json:"lecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLectureByNameResponse) Reset() {
	*x = GetLectureByNameResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureByNameResponse) ProtoMessage() {}

func (x *GetLectureByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureByNameResponse.ProtoReflect.Descriptor instead.
func (*GetLectureByNameResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{7}
}

func (x *GetLectureByNameResponse) GetLecture() *Lecture {
	if x != nil {
		return x.Lecture
	}
	return nil
}

type GetLectureByNameQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecture       *LectureQuery          `protobuf:"bytes,1,opt,name=lecture,proto3" json:"lecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLectureByNameQueryResponse) Reset() {
	*x = GetLectureByNameQueryResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureByNameQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureByNameQueryResponse) ProtoMessage() {}

func (x *GetLectureByNameQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureByNameQueryResponse.ProtoReflect.Descriptor instead.
func (*GetLectureByNameQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{8}
}

func (x *GetLectureByNameQueryResponse) GetLecture() *LectureQuery {
	if x != nil {
		return x.Lecture
	}
	return nil
}

type GetLectureByIDQueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecture       *LectureQuery          `protobuf:"bytes,1,opt,name=lecture,proto3" json:"lecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLectureByIDQueryResponse) Reset() {
	*x = GetLectureByIDQueryResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLectureByIDQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLectureByIDQueryResponse) ProtoMessage() {}

func (x *GetLectureByIDQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLectureByIDQueryResponse.ProtoReflect.Descriptor instead.
func (*GetLectureByIDQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{9}
}

func (x *GetLectureByIDQueryResponse) GetLecture() *LectureQuery {
	if x != nil {
		return x.Lecture
	}
	return nil
}

type ListLecturesByEventIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventId       int64                  `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLecturesByEventIDRequest) Reset() {
	*x = ListLecturesByEventIDRequest{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturesByEventIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturesByEventIDRequest) ProtoMessage() {}

func (x *ListLecturesByEventIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturesByEventIDRequest.ProtoReflect.Descriptor instead.
func (*ListLecturesByEventIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{10}
}

func (x *ListLecturesByEventIDRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *ListLecturesByEventIDRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturesByEventIDRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLecturesByEventIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lectures      []*LectureQuery        `protobuf:"bytes,1,rep,name=lectures,proto3" json:"lectures,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLecturesByEventIDResponse) Reset() {
	*x = ListLecturesByEventIDResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturesByEventIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturesByEventIDResponse) ProtoMessage() {}

func (x *ListLecturesByEventIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturesByEventIDResponse.ProtoReflect.Descriptor instead.
func (*ListLecturesByEventIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{11}
}

func (x *ListLecturesByEventIDResponse) GetLectures() []*LectureQuery {
	if x != nil {
		return x.Lectures
	}
	return nil
}

func (x *ListLecturesByEventIDResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListLecturesByEventIDResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturesByEventIDResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturesByEventIDResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type ListLecturesByLecturerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LecturerId    int64                  `protobuf:"varint,1,opt,name=lecturer_id,json=lecturerId,proto3" json:"lecturer_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLecturesByLecturerIDRequest) Reset() {
	*x = ListLecturesByLecturerIDRequest{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturesByLecturerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturesByLecturerIDRequest) ProtoMessage() {}

func (x *ListLecturesByLecturerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturesByLecturerIDRequest.ProtoReflect.Descriptor instead.
func (*ListLecturesByLecturerIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{12}
}

func (x *ListLecturesByLecturerIDRequest) GetLecturerId() int64 {
	if x != nil {
		return x.LecturerId
	}
	return 0
}

func (x *ListLecturesByLecturerIDRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturesByLecturerIDRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListLecturesByLecturerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lectures      []*LectureQuery        `protobuf:"bytes,1,rep,name=lectures,proto3" json:"lectures,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	HasNextPage   bool                   `protobuf:"varint,5,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLecturesByLecturerIDResponse) Reset() {
	*x = ListLecturesByLecturerIDResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLecturesByLecturerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLecturesByLecturerIDResponse) ProtoMessage() {}

func (x *ListLecturesByLecturerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLecturesByLecturerIDResponse.ProtoReflect.Descriptor instead.
func (*ListLecturesByLecturerIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{13}
}

func (x *ListLecturesByLecturerIDResponse) GetLectures() []*LectureQuery {
	if x != nil {
		return x.Lectures
	}
	return nil
}

func (x *ListLecturesByLecturerIDResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ListLecturesByLecturerIDResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLecturesByLecturerIDResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListLecturesByLecturerIDResponse) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

type UpdateLectureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LecturerId    int64                  `protobuf:"varint,2,opt,name=lecturer_id,json=lecturerId,proto3" json:"lecturer_id,omitempty"`
	EventId       int64                  `protobuf:"varint,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,5,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLectureRequest) Reset() {
	*x = UpdateLectureRequest{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLectureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLectureRequest) ProtoMessage() {}

func (x *UpdateLectureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLectureRequest.ProtoReflect.Descriptor instead.
func (*UpdateLectureRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateLectureRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateLectureRequest) GetLecturerId() int64 {
	if x != nil {
		return x.LecturerId
	}
	return 0
}

func (x *UpdateLectureRequest) GetEventId() int64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *UpdateLectureRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLectureRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type DeleteLectureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLectureRequest) Reset() {
	*x = DeleteLectureRequest{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLectureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLectureRequest) ProtoMessage() {}

func (x *DeleteLectureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLectureRequest.ProtoReflect.Descriptor instead.
func (*DeleteLectureRequest) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteLectureRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteLectureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lecture       *Lecture               `protobuf:"bytes,1,opt,name=lecture,proto3" json:"lecture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLectureResponse) Reset() {
	*x = DeleteLectureResponse{}
	mi := &file_proto_lecture_lecture_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLectureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLectureResponse) ProtoMessage() {}

func (x *DeleteLectureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_lecture_lecture_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLectureResponse.ProtoReflect.Descriptor instead.
func (*DeleteLectureResponse) Descriptor() ([]byte, []int) {
	return file_proto_lecture_lecture_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteLectureResponse) GetLecture() *Lecture {
	if x != nil {
		return x.Lecture
	}
	return nil
}

var File_proto_lecture_lecture_proto protoreflect.FileDescriptor

const file_proto_lecture_lecture_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/lecture/lecture.proto\x12\alecture\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1dproto/lecturer/lecturer.proto\x1a\x17proto/event/event.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb8\x01\n" +
	"\aLecture\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12.\n" +
	"\blecturer\x18\x02 \x01(\v2\x12.lecturer.LecturerR\blecturer\x12\"\n" +
	"\x05event\x18\x03 \x01(\v2\f.event.EventR\x05event\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x125\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\xdf\x05\n" +
	"\fLectureQuery\x12\x1d\n" +
	"\n" +
	"lecture_id\x18\x01 \x01(\x03R\tlectureId\x12\x1f\n" +
	"\vlecturer_id\x18\x02 \x01(\x03R\n" +
	"lecturerId\x12,\n" +
	"\x12lecturer_full_name\x18\x03 \x01(\tR\x10lecturerFullName\x12%\n" +
	"\x0electurer_title\x18\x04 \x01(\tR\rlecturerTitle\x12=\n" +
	"\x1blecturer_field_of_expertise\x18\x05 \x01(\tR\x18lecturerFieldOfExpertise\x12\x19\n" +
	"\bevent_id\x18\x06 \x01(\x03R\aeventId\x12\x1d\n" +
	"\n" +
	"event_name\x18\a \x01(\tR\teventName\x124\n" +
	"\x16event_cotisation_price\x18\b \x01(\x01R\x14eventCotisationPrice\x12!\n" +
	"\fevent_agenda\x18\t \x01(\tR\veventAgenda\x12\x1d\n" +
	"\n" +
	"event_type\x18\n" +
	" \x01(\tR\teventType\x12B\n" +
	"\x0fevent_date_time\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\reventDateTime\x12\x1f\n" +
	"\vlocation_id\x18\f \x01(\x03R\n" +
	"locationId\x12#\n" +
	"\rlocation_name\x18\r \x01(\tR\flocationName\x12)\n" +
	"\x10location_address\x18\x0e \x01(\tR\x0flocationAddress\x12+\n" +
	"\x11location_capacity\x18\x0f \x01(\x03R\x10locationCapacity\x12!\n" +
	"\flecture_name\x18\x10 \x01(\tR\vlectureName\x12D\n" +
	"\x10lecture_duration\x18\x11 \x01(\v2\x19.google.protobuf.DurationR\x0flectureDuration\"\x9d\x01\n" +
	"\x14CreateLectureRequest\x12\x1f\n" +
	"\vlecturer_id\x18\x01 \x01(\x03R\n" +
	"lecturerId\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\"C\n" +
	"\x15CreateLectureResponse\x12*\n" +
	"\alecture\x18\x01 \x01(\v2\x10.lecture.LectureR\alecture\"'\n" +
	"\x15GetLectureByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"D\n" +
	"\x16GetLectureByIDResponse\x12*\n" +
	"\alecture\x18\x01 \x01(\v2\x10.lecture.LectureR\alecture\"-\n" +
	"\x17GetLectureByNameRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"F\n" +
	"\x18GetLectureByNameResponse\x12*\n" +
	"\alecture\x18\x01 \x01(\v2\x10.lecture.LectureR\alecture\"P\n" +
	"\x1dGetLectureByNameQueryResponse\x12/\n" +
	"\alecture\x18\x01 \x01(\v2\x15.lecture.LectureQueryR\alecture\"N\n" +
	"\x1bGetLectureByIDQueryResponse\x12/\n" +
	"\alecture\x18\x01 \x01(\v2\x15.lecture.LectureQueryR\alecture\"j\n" +
	"\x1cListLecturesByEventIDRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xc8\x01\n" +
	"\x1dListLecturesByEventIDResponse\x121\n" +
	"\blectures\x18\x01 \x03(\v2\x15.lecture.LectureQueryR\blectures\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\"s\n" +
	"\x1fListLecturesByLecturerIDRequest\x12\x1f\n" +
	"\vlecturer_id\x18\x01 \x01(\x03R\n" +
	"lecturerId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xcb\x01\n" +
	" ListLecturesByLecturerIDResponse\x121\n" +
	"\blectures\x18\x01 \x03(\v2\x15.lecture.LectureQueryR\blectures\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\x12\"\n" +
	"\rhas_next_page\x18\x05 \x01(\bR\vhasNextPage\"\xad\x01\n" +
	"\x14UpdateLectureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vlecturer_id\x18\x02 \x01(\x03R\n" +
	"lecturerId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\x03R\aeventId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x125\n" +
	"\bduration\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bduration\"&\n" +
	"\x14DeleteLectureRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"C\n" +
	"\x15DeleteLectureResponse\x12*\n" +
	"\alecture\x18\x01 \x01(\v2\x10.lecture.LectureR\alecture2\x95\x05\n" +
	"\x0eLectureService\x12P\n" +
	"\rCreateLecture\x12\x1d.lecture.CreateLectureRequest\x1a\x1e.lecture.CreateLectureResponse\"\x00\x12H\n" +
	"\rUpdateLecture\x12\x1d.lecture.UpdateLectureRequest\x1a\x16.google.protobuf.Empty\"\x00\x12P\n" +
	"\rDeleteLecture\x12\x1d.lecture.DeleteLectureRequest\x1a\x1e.lecture.DeleteLectureResponse\"\x00\x12X\n" +
	"\x0eGetLectureByID\x12\x1e.lecture.GetLectureByIDRequest\x1a$.lecture.GetLectureByIDQueryResponse\"\x00\x12^\n" +
	"\x10GetLectureByName\x12 .lecture.GetLectureByNameRequest\x1a&.lecture.GetLectureByNameQueryResponse\"\x00\x12h\n" +
	"\x15ListLecturesByEventID\x12%.lecture.ListLecturesByEventIDRequest\x1a&.lecture.ListLecturesByEventIDResponse\"\x00\x12q\n" +
	"\x18ListLecturesByLecturerID\x12(.lecture.ListLecturesByLecturerIDRequest\x1a).lecture.ListLecturesByLecturerIDResponse\"\x00BLZJgithub.com/LukaDervisevic/MikroservisnaArhitekturaISProjekat/proto/lectureb\x06proto3"

var (
	file_proto_lecture_lecture_proto_rawDescOnce sync.Once
	file_proto_lecture_lecture_proto_rawDescData []byte
)

func file_proto_lecture_lecture_proto_rawDescGZIP() []byte {
	file_proto_lecture_lecture_proto_rawDescOnce.Do(func() {
		file_proto_lecture_lecture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_lecture_lecture_proto_rawDesc), len(file_proto_lecture_lecture_proto_rawDesc)))
	})
	return file_proto_lecture_lecture_proto_rawDescData
}

var file_proto_lecture_lecture_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_lecture_lecture_proto_goTypes = []any{
	(*Lecture)(nil),                          // 0: lecture.Lecture
	(*LectureQuery)(nil),                     // 1: lecture.LectureQuery
	(*CreateLectureRequest)(nil),             // 2: lecture.CreateLectureRequest
	(*CreateLectureResponse)(nil),            // 3: lecture.CreateLectureResponse
	(*GetLectureByIDRequest)(nil),            // 4: lecture.GetLectureByIDRequest
	(*GetLectureByIDResponse)(nil),           // 5: lecture.GetLectureByIDResponse
	(*GetLectureByNameRequest)(nil),          // 6: lecture.GetLectureByNameRequest
	(*GetLectureByNameResponse)(nil),         // 7: lecture.GetLectureByNameResponse
	(*GetLectureByNameQueryResponse)(nil),    // 8: lecture.GetLectureByNameQueryResponse
	(*GetLectureByIDQueryResponse)(nil),      // 9: lecture.GetLectureByIDQueryResponse
	(*ListLecturesByEventIDRequest)(nil),     // 10: lecture.ListLecturesByEventIDRequest
	(*ListLecturesByEventIDResponse)(nil),    // 11: lecture.ListLecturesByEventIDResponse
	(*ListLecturesByLecturerIDRequest)(nil),  // 12: lecture.ListLecturesByLecturerIDRequest
	(*ListLecturesByLecturerIDResponse)(nil), // 13: lecture.ListLecturesByLecturerIDResponse
	(*UpdateLectureRequest)(nil),             // 14: lecture.UpdateLectureRequest
	(*DeleteLectureRequest)(nil),             // 15: lecture.DeleteLectureRequest
	(*DeleteLectureResponse)(nil),            // 16: lecture.DeleteLectureResponse
	(*lecturer.Lecturer)(nil),                // 17: lecturer.Lecturer
	(*event.Event)(nil),                      // 18: event.Event
	(*durationpb.Duration)(nil),              // 19: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),            // 20: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                    // 21: google.protobuf.Empty
}
var file_proto_lecture_lecture_proto_depIdxs = []int32{
	17, // 0: lecture.Lecture.lecturer:type_name -> lecturer.Lecturer
	18, // 1: lecture.Lecture.event:type_name -> event.Event
	19, // 2: lecture.Lecture.duration:type_name -> google.protobuf.Duration
	20, // 3: lecture.LectureQuery.event_date_time:type_name -> google.protobuf.Timestamp
	19, // 4: lecture.LectureQuery.lecture_duration:type_name -> google.protobuf.Duration
	19, // 5: lecture.CreateLectureRequest.duration:type_name -> google.protobuf.Duration
	0,  // 6: lecture.CreateLectureResponse.lecture:type_name -> lecture.Lecture
	0,  // 7: lecture.GetLectureByIDResponse.lecture:type_name -> lecture.Lecture
	0,  // 8: lecture.GetLectureByNameResponse.lecture:type_name -> lecture.Lecture
	1,  // 9: lecture.GetLectureByNameQueryResponse.lecture:type_name -> lecture.LectureQuery
	1,  // 10: lecture.GetLectureByIDQueryResponse.lecture:type_name -> lecture.LectureQuery
	1,  // 11: lecture.ListLecturesByEventIDResponse.lectures:type_name -> lecture.LectureQuery
	1,  // 12: lecture.ListLecturesByLecturerIDResponse.lectures:type_name -> lecture.LectureQuery
	19, // 13: lecture.UpdateLectureRequest.duration:type_name -> google.protobuf.Duration
	0,  // 14: lecture.DeleteLectureResponse.lecture:type_name -> lecture.Lecture
	2,  // 15: lecture.LectureService.CreateLecture:input_type -> lecture.CreateLectureRequest
	14, // 16: lecture.LectureService.UpdateLecture:input_type -> lecture.UpdateLectureRequest
	15, // 17: lecture.LectureService.DeleteLecture:input_type -> lecture.DeleteLectureRequest
	4,  // 18: lecture.LectureService.GetLectureByID:input_type -> lecture.GetLectureByIDRequest
	6,  // 19: lecture.LectureService.GetLectureByName:input_type -> lecture.GetLectureByNameRequest
	10, // 20: lecture.LectureService.ListLecturesByEventID:input_type -> lecture.ListLecturesByEventIDRequest
	12, // 21: lecture.LectureService.ListLecturesByLecturerID:input_type -> lecture.ListLecturesByLecturerIDRequest
	3,  // 22: lecture.LectureService.CreateLecture:output_type -> lecture.CreateLectureResponse
	21, // 23: lecture.LectureService.UpdateLecture:output_type -> google.protobuf.Empty
	16, // 24: lecture.LectureService.DeleteLecture:output_type -> lecture.DeleteLectureResponse
	9,  // 25: lecture.LectureService.GetLectureByID:output_type -> lecture.GetLectureByIDQueryResponse
	8,  // 26: lecture.LectureService.GetLectureByName:output_type -> lecture.GetLectureByNameQueryResponse
	11, // 27: lecture.LectureService.ListLecturesByEventID:output_type -> lecture.ListLecturesByEventIDResponse
	13, // 28: lecture.LectureService.ListLecturesByLecturerID:output_type -> lecture.ListLecturesByLecturerIDResponse
	22, // [22:29] is the sub-list for method output_type
	15, // [15:22] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_lecture_lecture_proto_init() }
func file_proto_lecture_lecture_proto_init() {
	if File_proto_lecture_lecture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_lecture_lecture_proto_rawDesc), len(file_proto_lecture_lecture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_lecture_lecture_proto_goTypes,
		DependencyIndexes: file_proto_lecture_lecture_proto_depIdxs,
		MessageInfos:      file_proto_lecture_lecture_proto_msgTypes,
	}.Build()
	File_proto_lecture_lecture_proto = out.File
	file_proto_lecture_lecture_proto_goTypes = nil
	file_proto_lecture_lecture_proto_depIdxs = nil
}
