// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lecture

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LectureServiceClient is the client API for LectureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LectureServiceClient interface {
	// Create lecture
	CreateLecture(ctx context.Context, in *CreateLectureRequest, opts ...grpc.CallOption) (*CreateLectureResponse, error)
	// Update lecture
	UpdateLecture(ctx context.Context, in *UpdateLectureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// Delete lecture
	DeleteLecture(ctx context.Context, in *DeleteLectureRequest, opts ...grpc.CallOption) (*DeleteLectureResponse, error)
	// Get lecture by id
	GetLectureByID(ctx context.Context, in *GetLectureByIDRequest, opts ...grpc.CallOption) (*GetLectureByIDResponse, error)
	// Get lecture by name
	GetLectureByName(ctx context.Context, in *GetLectureByNameRequest, opts ...grpc.CallOption) (*GetLectureByNameResponse, error)
	// List lecture by event id
	ListLecturesByEventID(ctx context.Context, in *ListLecturesByEventIDRequest, opts ...grpc.CallOption) (*ListLecturesByEventIDResponse, error)
	// List lecture by leturer id
	ListLecturesByLecturerID(ctx context.Context, in *ListLecturesByLecturerIDRequest, opts ...grpc.CallOption) (*ListLecturesByLecturerIDResponse, error)
}

type lectureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLectureServiceClient(cc grpc.ClientConnInterface) LectureServiceClient {
	return &lectureServiceClient{cc}
}

func (c *lectureServiceClient) CreateLecture(ctx context.Context, in *CreateLectureRequest, opts ...grpc.CallOption) (*CreateLectureResponse, error) {
	out := new(CreateLectureResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/CreateLecture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) UpdateLecture(ctx context.Context, in *UpdateLectureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/UpdateLecture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) DeleteLecture(ctx context.Context, in *DeleteLectureRequest, opts ...grpc.CallOption) (*DeleteLectureResponse, error) {
	out := new(DeleteLectureResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/DeleteLecture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) GetLectureByID(ctx context.Context, in *GetLectureByIDRequest, opts ...grpc.CallOption) (*GetLectureByIDResponse, error) {
	out := new(GetLectureByIDResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/GetLectureByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) GetLectureByName(ctx context.Context, in *GetLectureByNameRequest, opts ...grpc.CallOption) (*GetLectureByNameResponse, error) {
	out := new(GetLectureByNameResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/GetLectureByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) ListLecturesByEventID(ctx context.Context, in *ListLecturesByEventIDRequest, opts ...grpc.CallOption) (*ListLecturesByEventIDResponse, error) {
	out := new(ListLecturesByEventIDResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/ListLecturesByEventID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) ListLecturesByLecturerID(ctx context.Context, in *ListLecturesByLecturerIDRequest, opts ...grpc.CallOption) (*ListLecturesByLecturerIDResponse, error) {
	out := new(ListLecturesByLecturerIDResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/ListLecturesByLecturerID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LectureServiceServer is the server API for LectureService service.
// All implementations must embed UnimplementedLectureServiceServer
// for forward compatibility
type LectureServiceServer interface {
	// Create lecture
	CreateLecture(context.Context, *CreateLectureRequest) (*CreateLectureResponse, error)
	// Update lecture
	UpdateLecture(context.Context, *UpdateLectureRequest) (*emptypb.Empty, error)
	// Delete lecture
	DeleteLecture(context.Context, *DeleteLectureRequest) (*DeleteLectureResponse, error)
	// Get lecture by id
	GetLectureByID(context.Context, *GetLectureByIDRequest) (*GetLectureByIDResponse, error)
	// Get lecture by name
	GetLectureByName(context.Context, *GetLectureByNameRequest) (*GetLectureByNameResponse, error)
	// List lecture by event id
	ListLecturesByEventID(context.Context, *ListLecturesByEventIDRequest) (*ListLecturesByEventIDResponse, error)
	// List lecture by leturer id
	ListLecturesByLecturerID(context.Context, *ListLecturesByLecturerIDRequest) (*ListLecturesByLecturerIDResponse, error)
	mustEmbedUnimplementedLectureServiceServer()
}

// UnimplementedLectureServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLectureServiceServer struct {
}

func (UnimplementedLectureServiceServer) CreateLecture(context.Context, *CreateLectureRequest) (*CreateLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLecture not implemented")
}
func (UnimplementedLectureServiceServer) UpdateLecture(context.Context, *UpdateLectureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLecture not implemented")
}
func (UnimplementedLectureServiceServer) DeleteLecture(context.Context, *DeleteLectureRequest) (*DeleteLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLecture not implemented")
}
func (UnimplementedLectureServiceServer) GetLectureByID(context.Context, *GetLectureByIDRequest) (*GetLectureByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLectureByID not implemented")
}
func (UnimplementedLectureServiceServer) GetLectureByName(context.Context, *GetLectureByNameRequest) (*GetLectureByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLectureByName not implemented")
}
func (UnimplementedLectureServiceServer) ListLecturesByEventID(context.Context, *ListLecturesByEventIDRequest) (*ListLecturesByEventIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLecturesByEventID not implemented")
}
func (UnimplementedLectureServiceServer) ListLecturesByLecturerID(context.Context, *ListLecturesByLecturerIDRequest) (*ListLecturesByLecturerIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLecturesByLecturerID not implemented")
}
func (UnimplementedLectureServiceServer) mustEmbedUnimplementedLectureServiceServer() {}

// UnsafeLectureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LectureServiceServer will
// result in compilation errors.
type UnsafeLectureServiceServer interface {
	mustEmbedUnimplementedLectureServiceServer()
}

func RegisterLectureServiceServer(s *grpc.Server, srv LectureServiceServer) {
	s.RegisterService(&_LectureService_serviceDesc, srv)
}

func _LectureService_CreateLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).CreateLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/CreateLecture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).CreateLecture(ctx, req.(*CreateLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_UpdateLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).UpdateLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/UpdateLecture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).UpdateLecture(ctx, req.(*UpdateLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_DeleteLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).DeleteLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/DeleteLecture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).DeleteLecture(ctx, req.(*DeleteLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_GetLectureByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLectureByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).GetLectureByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/GetLectureByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).GetLectureByID(ctx, req.(*GetLectureByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_GetLectureByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLectureByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).GetLectureByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/GetLectureByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).GetLectureByName(ctx, req.(*GetLectureByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_ListLecturesByEventID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLecturesByEventIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).ListLecturesByEventID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/ListLecturesByEventID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).ListLecturesByEventID(ctx, req.(*ListLecturesByEventIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_ListLecturesByLecturerID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLecturesByLecturerIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).ListLecturesByLecturerID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/ListLecturesByLecturerID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).ListLecturesByLecturerID(ctx, req.(*ListLecturesByLecturerIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _LectureService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lecture.LectureService",
	HandlerType: (*LectureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLecture",
			Handler:    _LectureService_CreateLecture_Handler,
		},
		{
			MethodName: "UpdateLecture",
			Handler:    _LectureService_UpdateLecture_Handler,
		},
		{
			MethodName: "DeleteLecture",
			Handler:    _LectureService_DeleteLecture_Handler,
		},
		{
			MethodName: "GetLectureByID",
			Handler:    _LectureService_GetLectureByID_Handler,
		},
		{
			MethodName: "GetLectureByName",
			Handler:    _LectureService_GetLectureByName_Handler,
		},
		{
			MethodName: "ListLecturesByEventID",
			Handler:    _LectureService_ListLecturesByEventID_Handler,
		},
		{
			MethodName: "ListLecturesByLecturerID",
			Handler:    _LectureService_ListLecturesByLecturerID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/lecture/lecture.proto",
}
