// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package lecture

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// LectureServiceClient is the client API for LectureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LectureServiceClient interface {
	CreateLecture(ctx context.Context, in *CreateLectureRequest, opts ...grpc.CallOption) (*CreateLectureResponse, error)
	GetLectureByName(ctx context.Context, in *GetLectureRequest, opts ...grpc.CallOption) (*GetLectureResponse, error)
	UpdateLecture(ctx context.Context, in *UpdateLectureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteLecture(ctx context.Context, in *DeleteLectureRequest, opts ...grpc.CallOption) (*DeleteLectureResponse, error)
	GetLectures(ctx context.Context, in *GetLecturesRequest, opts ...grpc.CallOption) (LectureService_GetLecturesClient, error)
}

type lectureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLectureServiceClient(cc grpc.ClientConnInterface) LectureServiceClient {
	return &lectureServiceClient{cc}
}

func (c *lectureServiceClient) CreateLecture(ctx context.Context, in *CreateLectureRequest, opts ...grpc.CallOption) (*CreateLectureResponse, error) {
	out := new(CreateLectureResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/CreateLecture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) GetLectureByName(ctx context.Context, in *GetLectureRequest, opts ...grpc.CallOption) (*GetLectureResponse, error) {
	out := new(GetLectureResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/GetLectureByName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) UpdateLecture(ctx context.Context, in *UpdateLectureRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/UpdateLecture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) DeleteLecture(ctx context.Context, in *DeleteLectureRequest, opts ...grpc.CallOption) (*DeleteLectureResponse, error) {
	out := new(DeleteLectureResponse)
	err := c.cc.Invoke(ctx, "/lecture.LectureService/DeleteLecture", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lectureServiceClient) GetLectures(ctx context.Context, in *GetLecturesRequest, opts ...grpc.CallOption) (LectureService_GetLecturesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LectureService_serviceDesc.Streams[0], "/lecture.LectureService/GetLectures", opts...)
	if err != nil {
		return nil, err
	}
	x := &lectureServiceGetLecturesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LectureService_GetLecturesClient interface {
	Recv() (*GetLectureResponse, error)
	grpc.ClientStream
}

type lectureServiceGetLecturesClient struct {
	grpc.ClientStream
}

func (x *lectureServiceGetLecturesClient) Recv() (*GetLectureResponse, error) {
	m := new(GetLectureResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LectureServiceServer is the server API for LectureService service.
// All implementations must embed UnimplementedLectureServiceServer
// for forward compatibility
type LectureServiceServer interface {
	CreateLecture(context.Context, *CreateLectureRequest) (*CreateLectureResponse, error)
	GetLectureByName(context.Context, *GetLectureRequest) (*GetLectureResponse, error)
	UpdateLecture(context.Context, *UpdateLectureRequest) (*emptypb.Empty, error)
	DeleteLecture(context.Context, *DeleteLectureRequest) (*DeleteLectureResponse, error)
	GetLectures(*GetLecturesRequest, LectureService_GetLecturesServer) error
	mustEmbedUnimplementedLectureServiceServer()
}

// UnimplementedLectureServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLectureServiceServer struct {
}

func (UnimplementedLectureServiceServer) CreateLecture(context.Context, *CreateLectureRequest) (*CreateLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLecture not implemented")
}
func (UnimplementedLectureServiceServer) GetLectureByName(context.Context, *GetLectureRequest) (*GetLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLectureByName not implemented")
}
func (UnimplementedLectureServiceServer) UpdateLecture(context.Context, *UpdateLectureRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLecture not implemented")
}
func (UnimplementedLectureServiceServer) DeleteLecture(context.Context, *DeleteLectureRequest) (*DeleteLectureResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLecture not implemented")
}
func (UnimplementedLectureServiceServer) GetLectures(*GetLecturesRequest, LectureService_GetLecturesServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLectures not implemented")
}
func (UnimplementedLectureServiceServer) mustEmbedUnimplementedLectureServiceServer() {}

// UnsafeLectureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LectureServiceServer will
// result in compilation errors.
type UnsafeLectureServiceServer interface {
	mustEmbedUnimplementedLectureServiceServer()
}

func RegisterLectureServiceServer(s *grpc.Server, srv LectureServiceServer) {
	s.RegisterService(&_LectureService_serviceDesc, srv)
}

func _LectureService_CreateLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).CreateLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/CreateLecture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).CreateLecture(ctx, req.(*CreateLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_GetLectureByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).GetLectureByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/GetLectureByName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).GetLectureByName(ctx, req.(*GetLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_UpdateLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).UpdateLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/UpdateLecture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).UpdateLecture(ctx, req.(*UpdateLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_DeleteLecture_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLectureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LectureServiceServer).DeleteLecture(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lecture.LectureService/DeleteLecture",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LectureServiceServer).DeleteLecture(ctx, req.(*DeleteLectureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LectureService_GetLectures_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLecturesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LectureServiceServer).GetLectures(m, &lectureServiceGetLecturesServer{stream})
}

type LectureService_GetLecturesServer interface {
	Send(*GetLectureResponse) error
	grpc.ServerStream
}

type lectureServiceGetLecturesServer struct {
	grpc.ServerStream
}

func (x *lectureServiceGetLecturesServer) Send(m *GetLectureResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LectureService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lecture.LectureService",
	HandlerType: (*LectureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLecture",
			Handler:    _LectureService_CreateLecture_Handler,
		},
		{
			MethodName: "GetLectureByName",
			Handler:    _LectureService_GetLectureByName_Handler,
		},
		{
			MethodName: "UpdateLecture",
			Handler:    _LectureService_UpdateLecture_Handler,
		},
		{
			MethodName: "DeleteLecture",
			Handler:    _LectureService_DeleteLecture_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLectures",
			Handler:       _LectureService_GetLectures_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/lecture/lecture.proto",
}
