name: ci_lecturer_production.yml
on:
  pull_request:
    paths:
      - 'lecturer-service/**'
    branches:
      - 'main'

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.26.1'

      - name: Build project
        run: go build -v ./lecturer-service/...

      - name: Run tests
        run: go test -v ./lecturer-service/...

  docker-build-and-test:
    needs: build-and-test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Build a docker image
        run: docker build . --file ./lecturer-service/Dockerfile -t ${{secrets.DOCKERHUB_USER}}/lecturer-service-production:${{ github.sha }}

      #     TODO: Healthcheck endpoint for smoke test

      - name: Push to dockerhub
        run: docker push ${{ secrets.DOCKERHUB_USER }}/lecturer-service-production:${{ github.sha }}
